### ISSUE TITLE
Missing icons on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Rot127** [kabinspace/AstroVim#10]
Fresh install on `Ubuntu 20.04.3 LTS` and some icons were missing:

![nvim-b](https://user-images.githubusercontent.com/45763064/152646147-50e45a40-665e-4884-9a49-15442dc23a70.png)

What are the requirements for them?

**Comment by kabinspace** [comment]
For font icons to appear, you are required to install nerd fonts in your `/usr/share/fonts` directory and also use the downloaded fonts in your terminal.
Here is the link to nerd fonts: https://www.nerdfonts.com/font-downloads
The nerd font shown in the preview image is called JetBrainsMono Nerd Font though you can download any other nerd fonts if you like.

**Comment by Rot127** [comment]
Ah, use it in the terminal did it. Thanks for the hint.
