### ISSUE TITLE
:LspInstall not a valid command during setup

### ISSUE THREAD

**Issue by Normanras** [kabinspace/AstroVim#101]
Just installed Astrovim and all the inital setup commands (such as `:TSInstall`, `:PackerClean`, etc) worked, except for `:LspInstall`. I was trying `pyright` or `python` after the command.

The error I'm getting is that it is not a valid command. I'm looking through my settings.lua and don't see anything for LSP setup/settings. What am I missing?

I may have to restart my install because this is also the screen I'm getting when I run `nvim +PackerSync` �

<img width="1361" alt="Astrovim Dash" src="https://user-images.githubusercontent.com/44226464/155848752-03bd6316-cd2d-4315-9cdc-fe743270ea6d.png">
�

EDIT: Moved to a different machine with the same OS, same privileges, etc and the install worked. So I'll have to go back to my other machine and reinstall. 

However, one thing did persist, and that's the green screen. One dark theme doesn't seem to want to work.

I'm seeing #66 where AstroVim is linux focused. Does that count for all unix machines? I'm on a mac for both machines.

**Comment by mehalter** [comment]
@Normanras have you still been experiencing issues with AstroVim on Mac? I know a couple people running it on Mac OSX without any issues

**Comment by Normanras** [comment]
I ended up scrapping using pre-made dot files like Astrovim and starting from scratch. I had some weird permission issues with subfolders within `.local/../../packer` and once I reconfigured them, nvim and everything worked much better. There are still some weird errors, but I put so much work in building from scratch that I haven't tried Astro again.

**Comment by mehalter** [comment]
@Normanras ah I see, the native terminal doesn't support true color so you will need to use something like iTerm 2 or another mac terminal that has true color support.

**Comment by mehalter** [comment]
This is a good thing that we need to mention in the README. Thanks for pointing this out!
