### ISSUE TITLE
New install, nothing is working

### ISSUE THREAD

**Issue by ptn** [kabinspace/AstroVim#106]
I must be missing something fundamental then, can you help me figure out what it is?

I did:

```
$ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@iMac-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info


$ git clone https://github.com/kabinspace/AstroVim ~/.config/nvim
Cloning into '/Users/ptorres/.config/nvim'...
remote: Enumerating objects: 697, done.
remote: Counting objects: 100% (697/697), done.
remote: Compressing objects: 100% (550/550), done.
remote: Total 697 (delta 395), reused 216 (delta 110), pack-reused 0
Receiving objects: 100% (697/697), 732.84 KiB | 6.48 MiB/s, done.
Resolving deltas: 100% (395/395), done.


$ nvim +PackerSync
```

I am now in nvim with Packer saying everything is installed and up to date. The dashboard tells me I can do `SPC f f` to find a file, but pressing that combo doesn't do anything. According to which-key, it isn't actually mapped:

<img width="1792" alt="Screen Shot 2022-03-03 at 17 10 53" src="https://user-images.githubusercontent.com/98363/156667551-22d9758d-69b1-4cf8-827b-45d5de3dcc60.png">

I used good old `:e` to open a file, then tried `SPC g g` to open Lazygit. Here's what happened:

<img width="1250" alt="Screen Shot 2022-03-03 at 17 11 36" src="https://user-images.githubusercontent.com/98363/156667756-1a7ce902-1d6c-492e-b65c-37fed11a44eb.png">

I tried to return to the dashboard by doing `SPC d`, which which-key tells me is the thing to do. Again nothing happened. At bottom right, vim shows `<20d>d`, indicating that the `d` keystroke was interpreted on its own - nvim is now waiting for a motion or text object in order to delete text.

What command should I run to fix this? This is kinda smelling like I'm missing something Lua-related system-wide, though that's a guess on my part.

**Comment by kabinspace** [comment]
@ptn `space` + `ff` should work even though it is not defined in which-key since it is mapped in `lua/core/mappings.lua` for the lazygit problem, you need to [look](https://github.com/kabinspace/AstroVim/issues/15#issuecomment-1030742915) at this. Is any of the command except for `space` + `ff` working or nothing is working at all?

**Comment by ptn** [comment]
I tried `SPC f f` three times in a row, the first two it didn't but the third did. Now it works every time. Is there some sort of lazy loading?
