### ISSUE TITLE
Preventing automatic changing of current directory

### ISSUE THREAD

**Issue by lorefnon** [kabinspace/AstroVim#107]
Hello and thanks for creating this library. As a new comer to vim this setup has been a huge help towards me getting comfortable with vim. 

When I navigate between files there appears to be some integration that changes the current directory to the directory of working file. I'd like this to not happen because I want telescope livegrep to unconditionally return results relative to the directory where vim was spawned, I don't want the sidebar tree to keep changing root etc. 

I don't see `autochdir` or something to similar effect present in the config in this repo, but I could be missing something. Can you please help me understand what needs to be done to disable this behavior.

**Comment by mehalter** [comment]
@lorefnon are you seeing this when you select files with the nvim-tree explorer? I think that's the only thing that has cwd updating. Try adding this to the `overrides` table in the user `settings.lua` file:

```lua
["nvim-tree"] = {
  update_cwd = true,
},
```

**Comment by lorefnon** [comment]
Actually I just updated to latest main, and can no longer reproduce this behavior. I should have done that before opening the issue - my bad. Closing this.
