### ISSUE TITLE
tab lines w/strange coloring when overriding colorscheme from settings.lua

### ISSUE THREAD

**Issue by nonzer0** [kabinspace/AstroVim#116]
any idea why I might be getting these blue lines if i change `colorscheme` to tokyonight from `settings.lua`?
```lua
local config = {

  -- Set colorscheme
  colorscheme = "tokyonight",

--more things...
}
```

If I change it directly from the prompt i don't get the blue blues.

 <img width="293" alt="image" src="https://user-images.githubusercontent.com/1014594/156845548-4228fda4-9057-4417-8730-e249bea824b7.png">

**Comment by mehalter** [comment]
This should be coming from the `tokyonight` color scheme setting highlight groups for Indent Blankline. I haven't used this colorscheme before so idk what colors they use. But the lines are from Indent-Blankline and the colorscheme would set the highlight groups for the plugin
