### ISSUE TITLE
add support for windows user

### ISSUE THREAD

**Issue by bryant-the-coder** [kabinspace/AstroVim#119]
windows user requires this

 
 ​`require​(​"​nvim-treesitter.install​"​).​compilers​ ​=​ { ​"​clang​"​ } `
in their treesitter. please add this

**Comment by hunger** [comment]
What needs to go there depends entirely on the system setup!

Kn fact on most of my systems there is no compiler at all -- so tree-sitter skmply can not build its plugins there at all!

**Comment by bryant-the-coder** [comment]
but the compiler thing must be added into the readme to notify the users :))

**Comment by hunger** [comment]
Why? The `nvim-treesitter` docs say this is the default value: `M.compilers = { vim.fn.getenv('CC'), "cc", "gcc", "clang", "cl", "zig" }`.

So provided that the user has no broken mingw installed in `%PATH%`, all your change does is to avoid a look into the environment for `CC` and then a couple of stat calls for a set of directories (which are most likely cached by the OS already, considering that %PATH% is used a lot).

**Comment by mehalter** [comment]
@hunger brings up a good point with the `nvim-treesitter` defaults. I'm going to go ahead and close this.
