### ISSUE TITLE
ccls configuration

### ISSUE THREAD

**Issue by omalaspinas** [kabinspace/AstroVim#12]
Hello,
thanks a lot for this very cool project. Congrats.

I'm trying to setup ccls and configure it without much success I must say. Usually I was doing something like in my lsp.lua config file:

```
local lspconfig = require('lspconfig')

lspconfig.ccls.setup {
    root_dir = lspconfig.util.root_pattern("CMakeLists.txt", "build", "compile_commands.json", ".ccls", "compile_flags.txt");
    init_options = {
      compilationDatabaseDirectory = "build";
      index = {
        threads = 0;
      };
  }
}
```
Now I don't exactly know where to put these.

Thanks in advance.

Edit: forgot a "}" in my original post.

**Comment by kabinspace** [comment]
Can you try putting this in the bottom of `lua/configs/lsp/init.lua` file.

**Comment by omalaspinas** [comment]
Thanks for the quick answer!

Got an error:

```
Spawning language server with cmd: ccls failed. The language server is either not installed 
```
After manually adding the ccls to the PATH (it was detected normally before that) I get a new error

```
Error detected while processing CursorHold for "*":
method textDocument/codeAction is not supported by any of the servers registered for the current buffer.

**Comment by kabinspace** [comment]
@omalaspinas This error appears to be an error from a plugin called lspsaga, it's a plugin that gives us a code action prompt, lspsaga gives an error whenever the file type doesn't support code actions, in this case I would suggest you to disable code actions prompt which is located in `lua/configs/lsp/lspsaga.lua` file in [here](https://github.com/kabinspace/AstroVim/blob/0fdf5b48ebfa2008cf60697db6cc3f2032b8b136/lua/configs/lsp/lspsaga.lua#L21) it is set to true, you can set it to false. Let me know if this helped to solve your problem

**Comment by omalaspinas** [comment]
I changed it to false. The second error is gone, but it's like the addition had no effect. Still not using the config file in ccls.

**Comment by kabinspace** [comment]
@omalaspinas So, it's still not using the config that you posted above?

**Comment by omalaspinas** [comment]
No errors anymore but...

It does not look like it is working (the behavior is not the same as when I use the ccls  lsp directly with that config). I also tried modifying `lua/configs/lsp/lsp-installer.lua` and adding the config is `lua/configs/lsp/server-settings/ccls.lua` (random walik :)). This did not work either.

I will try to dig a bit more. If you have any idea they are welcome and I will keep you posted if I find anything (don't want to take too much of your time neither).

**Comment by kabinspace** [comment]
@omalaspinas The config that you want for lsp, is it about building and compiling c files? Can you elaborate on what you are actually trying to get out of it? I don't have any good knowledge on c or cpp so clearing me a little bit might be helpful for me as well

**Comment by omalaspinas** [comment]
@kabinspace It's about compiling a (complex) C++ project from a `compile_commands.json` file that is generated from a `CMakeLists.txt` file using `cmake` (https://gitlab.com/unigespc/palabos is the project that I am maintaining). Normally just putting the compute_commad.json in the correct folder does the trick (I'm not looking for the generation of the compute_commad.json file, but only to have continuous syntax checking and being able to jumb through the files). Thanks a lot for your help.

**Comment by kabinspace** [comment]
@omalaspinas Did you find the solution or any other alternatives for this problem? Sorry that I was not able to provide any helpful support.

**Comment by omalaspinas** [comment]
No need to be sorry. It's an open source project and your are being very helpful by just providing your code (and also answering questions)! 

I think I am converging towards identifying the problem. It probably has to do with the indexing ccls is supposed to do. I'll come back as soon as I have something more definitive.

**Comment by kabinspace** [comment]
@omalaspinas Should I close the issue?

**Comment by omalaspinas** [comment]
Yes do. Thanks!

**Comment by omalaspinas** [comment]
OK. Well I gave it a last try. In order to correct the problem I had to build ccls manually and copy it in the proper lsp_server directory. I think the problem is the CMAKE_PREFIX_PATH  that should point to the correct directory that is not set properly. Don't know how to make this "automatic" though...

**Comment by omalaspinas** [comment]
My intuition is that it's more an nvim-lsp-installer issue than an AstroVim issue. I guess you can close it.

**Comment by kabinspace** [comment]
Alright then, I'm going to close the issue but you can give us an update on the matter if you find anything helpful.
