### ISSUE TITLE
nvim-tree pinned?

### ISSUE THREAD

**Issue by abalmos** [kabinspace/AstroVim#121]
I have been operating without this pin:

https://github.com/kabinspace/AstroVim/blob/bad311582a493f64d49e35761eeb44a6eb3942af/lua/core/plugins.lua#L76

removed without any obvious issues. Is there a reason it is pinned?

**Comment by mehalter** [comment]
Recently nvim-tree was going through some very active development and it was quite unstable for a bit. Hopefully the rewriting had settled down. I'll check out the latest commits and we can probably drop the pinned commit here.
