### ISSUE TITLE
Bug display icon font

### ISSUE THREAD

**Issue by rtransat** [kabinspace/AstroVim#126]
Hi,

I have something weird with the folder icon closed (in nvimtree)

![image](https://user-images.githubusercontent.com/1011503/157078736-d83f1054-0d3d-42bc-95a0-5fa71df971f0.png)

The icon when the folder is closed (internal, migrations) is weird and I don't know why. I've installed this [package](https://aur.archlinux.org/packages/nerd-fonts-jetbrains-mono-160) and I use [MonoLisa](https://www.monolisa.dev/) font inside my terminal (allacrity)

I even do this `fc-cache -f -v`

**Comment by bryant-the-coder** [comment]
change your font

**Comment by rtransat** [comment]
Thank. I've installed JetBrains Mono NerdFont. Too bad for MonoLisa :disappointed:

**Comment by bryant-the-coder** [comment]
ah monolisa? that font didnt work for me... u bought monolisa?

**Comment by rtransat** [comment]
Yes I bought it.

**Comment by bryant-the-coder** [comment]
can share?

**Comment by bryant-the-coder** [comment]
@rtransat can you please share? :) interested in seeing how the fonts look
