### ISSUE TITLE
Tutorial for run code file

### ISSUE THREAD

**Issue by vnbubba** [kabinspace/AstroVim#13]
Can you write a tutorial for running a code file as cpp, c file? Many thanks!

**Comment by kabinspace** [comment]
@vnbubba I don't really program in c or cpp, can you tell me what would you like to know about them?

**Comment by vnbubba** [comment]
This is my keymap for run a C file as vimscript but I don't know how convert it to lua. 
` nnoremap <F5> :w <bar> !g++ -std=c++17 -O2 -Wall % -o %:r && %:r.exe <CR>`

**Comment by kabinspace** [comment]
@vnbubba Did the solution given by @hunger work for you?

**Comment by vnbubba** [comment]
> @vnbubba Did the solution given by @hunger work for you?

![image](https://user-images.githubusercontent.com/87162330/154187266-29a53aba-4c18-4d25-b846-762e1b762f46.png)
May I missed something?

**Comment by hunger** [comment]
So the mapping worked and you only need to work on the code you want to call:-)

**Comment by vnbubba** [comment]
> @vnbubba Did the solution given by @hunger work for you?

https://github.com/skywind3000/asyncrun.vim
Can you add this packer for AstroVim? Thanks
