### ISSUE TITLE
Change in Enter-Selection behavior

### ISSUE THREAD

**Issue by lorefnon** [kabinspace/AstroVim#130]
After pulling master I noticed that enter key no longer selects the top most completion in the menu of suggestions. After some digging in I traced it to [this change](https://github.com/kabinspace/AstroVim/commit/bad311582a493f64d49e35761eeb44a6eb3942af): 

```diff
-      ["<CR>"] = cmp.mapping.confirm { select = true },
+      ["<CR>"] = cmp.mapping.confirm(),
```

I am curious if this change was intentional ? While I can of course change it back in my own config, I think the previous behavior is more intuitive for users coming from other editors.

**Comment by mehalter** [comment]
@lorefnon this was a change I proposed. The explanation is here: https://github.com/kabinspace/AstroVim/pull/120

Mainly because I noticed if I'm at the end of a line and the last thing I typed triggers CMP for whatever reason and I want to do a new line pressing enter would complete even if I didn't want it to and what I had typed was what I wanted

**Comment by lorefnon** [comment]
Oh ok, I understand the motivation. I think I have myself been annoyed with this before and over time gotten habituated to first getting rid of any menus before subsequent editing. 

So while this requires some unlearning on my part, I won't suggest changing it back unless others find it inconvenient too.

**Comment by mehalter** [comment]
@lorefnon We are currently discussing ways to make it easier for the user to extend/override default behavior. Soon we will have a way for you to override this setting in the user settings :)

**Comment by mehalter** [comment]
@lorefnon , I have just opened a PR that will allow this, I have also included examples on the PR of the new functionality in terms of this exact question: https://github.com/kabinspace/AstroVim/pull/136

**Comment by lorefnon** [comment]
Nice, thanks for your work in this repo. Makes vim a lot more approachable.
