### ISSUE TITLE
Disable format on save for a specific LSP

### ISSUE THREAD

**Issue by rtransat** [kabinspace/AstroVim#131]
Hi.

I've created a intelephense.lua file inside lua/user/server-settings with the following content:

```lua
return {
  settings = {
    intelephense = {
      format = {
        enable = false
      }
    }
  }
}
```

I want to use null-ls for formatting php file and when I save the file I have a prompt with a question about which formater I want to use (intelephense or null-ls)

How to disable the format on save with the intelephense lsp?
From [this](https://github.com/bmewburn/intelephense-docs/blob/25dd5c348d3d019292c2294d9bf6348f98171790/installation.md#configuration-options) repo there is a section `"intelephense.format.enable"` but it doesn't work.

Before AstroVim I used [that](https://github.com/rtransat/dotfile/blob/master/dot_config%2Fnvim%2Flua%2Fmodules%2Flsp%2Fphp.lua) but I don't know if I can have access to the on_attach for each LSP.

**Comment by rtransat** [comment]
I found a solution. I following the README and add a `lsp_installer` options inside `overrides`:

```lua
lsp_installer = {
  server_registration_override = function(server, server_opts)
    -- Special code for rust.tools.nvim!
    if server.name == "intelephense" then
      on_attach = function(client)
        client.resolved_capabilities.document_formatting = false
        client.resolved_capabilities.document_range_formatting = false
      end
    end
  end,
},
```

But the default config from LSP is overide and I don't know how to enable the default config. Any ideas? For example when I highlight a variable there is no highlight anymore.

**Comment by mehalter** [comment]
@rtransat I haven't tried this because I don't have anything similar set up to give it a shot with, but could you try this?

```lua
lsp_installer = {
  server_registration_override = function(server, server_opts)
    -- Special code for rust.tools.nvim!
    if server.name == "intelephense" then
      on_attach = function(client, bufnr)
        client.resolved_capabilities.document_formatting = false
        client.resolved_capabilities.document_range_formatting = false
        server_opts.on_attach(client, bufnr)
      end
    end
  end,
},
```

**Comment by mehalter** [comment]
@rtransat I just opened a PR with a small change that would hopefully make this easier and less hacky (https://github.com/kabinspace/AstroVim/pull/139/files). Do you think you could try checking out this change and test if this is a better approach?

instead of the `server_registration_override` could you try doing this in the `overrides` table:

```lua
  local overrides = {
    lsp_installer = {
      on_attach_override = function(client, bufnr)
        if client.name == "intelephense" then
          client.resolved_capabilities.document_formatting = false
          client.resolved_capabilities.document_range_formatting = false
        end
      end,
    },
  }
```

**Comment by rtransat** [comment]
The first solution doesn't work. The second seems working.
