### ISSUE TITLE
CRLF line endings added when using null-ls to format document on windows

### ISSUE THREAD

**Issue by bradleybauer** [kabinspace/AstroVim#138]
I am using neovim v0.6.1 on windows and have added the yapf formatter to null-ls.lua in the user directory. When I format python code CRLF line endings (^M) are added to the end of most lines. How can I prevent this from happening?

**Comment by mehalter** [comment]
@bradleybauer, I believe this can be done with several different  file types to specify the formatting: 

https://github.com/google/yapf#formatting-style

I haven't tried this, but it looks like the most global way would be to use the following approach and fill in the style options that you want


> In the [style] section of a ~/.config/yapf/style file in your home directory.

**Comment by bradleybauer** [comment]
Adding `set ++ff=unix` to my settings.lua seems to have helped.
