### ISSUE TITLE
Not an editor command: PackerSync

### ISSUE THREAD

**Issue by DenverEllis** [kabinspace/AstroVim#14]
Long time emacs user (not about the editor wars) but I have used a fair bit of vim over the years. Caught wind of this from reddit and thought it would be a great first step to my ZorinOS rice. 

After creating the nvim folder in .config, cloning it, and running nvim I essentially have a vanilla instance running. The only present clues that I have is not having packer installed (clued by PackerSync not working,) but I have had no luck setting it up. Any ideas?

**Comment by kabinspace** [comment]
@DenverEllis That's very odd, it should have worked out of the box, packer should get automatically installed once you clone my repo, can you try deleting your nvim folder and doing a clone again?

**Comment by DenverEllis** [comment]
deleted ~/.config/nvim and ~/.local/share/nvim

Recloned into ~/.config/nvim and ran nvim +PackerSync


![Screenshot from 2022-02-05 15-51-41](https://user-images.githubusercontent.com/20245573/152660213-d235073c-71c5-45d7-9d2f-6bb4721bb725.png)

**Comment by DenverEllis** [comment]
I may have found the issue, seems like my repositories are still using version 0.4

After doing some background on Neovim, it seems like version 0.5 was quite the rage/excitement and is probably a requirement considering the changes to the Lua API. I will see if I can upgrade and report back.

**Comment by DenverEllis** [comment]
Fun and unintuitive error... My Neovim was out of date. Updating it did fix it. Debian and Ubuntu repositories are still serving 0.4

For others running into the same issue, here is my solution:

```
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt update
sudo apt upgrade
nvim +PackerSync
```

As of February 5th 2022, this installed Neovim 0.6.1 and solved my issue. 

Thanks for the swift reply @kabinspace !!!

**Comment by shubham1172** [comment]
If any one is coming here from Windows, your nvim configuration might be at `~/AppData/Local/nvim`.

> To find here that directory is exactly, use the command :echo stdpath('config') inside Neovim
https://jdhao.github.io/2018/11/15/neovim_configuration_windows/

**Comment by x-ray-s** [comment]
In windows, you may run the command below
```
git clone https://github.com/AstroNvim/AstroNvim ~/AppData/Local/nvim/
```
