### ISSUE TITLE
[Feature Request] Telescope Themes

### ISSUE THREAD

**Issue by cobcobs** [kabinspace/AstroVim#141]
Would it be possible to theme Telescope like in NvChad? I feel like it would make AstroVim more aesthetically pleasing. Something like this:
![image](https://user-images.githubusercontent.com/44166162/157612792-d9d8a468-719d-40f5-b88b-b51e874f212a.png)

Here's a similar issue: https://github.com/LunarVim/LunarVim/issues/2286

When getting rid of the visible border characters, the same thing should probably be done with other UI like packer, which-key, toggleterm, and lspsaga. This can already be achieved like this though:
```lua
local config = {
  -- more config
  overrides = {
    packer = {
      display = {
        prompt_border = "none",
      }
    },
    ["which-key"] = {
      window = {
        border = "none",
      }
    },
    toggleterm = {
      float_opts = {
        border = "none",
        highlights = {
          background = "NormalFloat"
        }
      }
    },
    lspsaga = {
      border_style = "none"
    }
  }
  -- even more config
}
```

I'm interested to hear your thoughts on this. Thanks!

**Comment by mehalter** [comment]
@cobcobs doing some testing and I have it looking like this so far


![2022-03-10_09:39:00_screenshot](https://user-images.githubusercontent.com/1591837/157684842-4a2f59fd-1141-4c89-8ec7-c2ba0e8a6ce1.png)

**Comment by mehalter** [comment]
@cobcobs the set up here is gotten from your other issue on LunarVim: https://github.com/LunarVim/LunarVim/issues/2286#issuecomment-1048208811

Basically for AstroVim this can be achieved just as easily:

1. Add the following block to your `settings.lua` in the `overrides` table:

```lua
  overrides = {
    telescope = {
      defaults = {
        prompt_prefix = "  ",
        borderchars = {
          prompt = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
          results = { "─", "▐", "─", "│", "╭", "▐", "▐", "╰" },
          preview = { " ", "│", " ", "▌", "▌", "╮", "╯", "▌" },
        },
        selection_caret = "  ",
        layout_config = {
          width = 0.90,
          height = 0.85,
          preview_cutoff = 120,
          horizontal = {
            preview_width = function(_, cols, _)
              return math.floor(cols * 0.6)
            end,
          },
          vertical = {
            width = 0.9,
            height = 0.95,
            preview_height = 0.5,
          },

          flex = {
            horizontal = {
              preview_width = 0.9,
            },
          },
        },
        layout_strategy = "horizontal",
      },
    },
  },
```

2. Create the `theme.lua` file in your `user/` folder with the contents:

```lua
local M = {}

M.hi_colors = function()
  local colors = {
    bg = "#16161D",
    bg_alt = "#1F1F28",
    fg = "#DCD7BA",
    green = "#76946A",
    red = "#E46876",
  }
  local color_binds = {
    bg = { group = "NormalFloat", property = "background" },
    bg_alt = { group = "Cursor", property = "foreground" },
    fg = { group = "Cursor", property = "background" },
    green = { group = "diffAdded", property = "foreground" },
    red = { group = "diffRemoved", property = "foreground" },
  }
  local function get_hl_by_name(name)
    local ret = vim.api.nvim_get_hl_by_name(name.group, true)
    return string.format("#%06x", ret[name.property])
  end
  for k, v in pairs(color_binds) do
    local found, color = pcall(get_hl_by_name, v)
    if found then
      colors[k] = color
    end
  end
  return colors
end

M.telescope_theme = function()
  local function set_bg(group, bg)
    vim.cmd("hi " .. group .. " guibg=" .. bg)
  end

  local function set_fg_bg(group, fg, bg)
    vim.cmd("hi " .. group .. " guifg=" .. fg .. " guibg=" .. bg)
  end

  local colors = M.hi_colors()
  set_fg_bg("TelescopeBorder", colors.bg_alt, colors.bg)
  set_fg_bg("TelescopePromptBorder", colors.bg, colors.bg)
  set_fg_bg("TelescopePromptNormal", colors.fg, colors.bg_alt)
  set_fg_bg("TelescopePromptPrefix", colors.red, colors.bg)
  set_fg_bg("TelescopePreviewTitle", colors.bg, colors.green)
  set_fg_bg("TelescopePromptTitle", colors.bg, colors.red)
  set_fg_bg("TelescopeResultsTitle", colors.bg, colors.bg)
  set_fg_bg("TelescopeResultsBorder", colors.bg, colors.bg)
  set_fg_bg("LvimInfoHeader", colors.bg, colors.green)
  set_fg_bg("LvimInfoIdentifier", colors.red, colors.bg_alt)
  set_bg("TelescopeSelection", colors.bg_alt)
  set_bg("TelescopeNormal", colors.bg)
end

return M
```

3. Add the following line to the `polish` function inside of the `settings.lua` file:

```lua
  polish = function()
    vim.cmd [[
      autocmd VimEnter * lua require("user.theme").telescope_theme()
    ]]
  end,
```

**Comment by cobcobs** [comment]
Thanks for your reply @mehalter! 

Do you see this becoming a default for AstroVim, or perhaps an opt in feature like this https://github.com/abzcoding/lvim/commit/99b3796a363a5158399724200e9c109190abaa62? Thanks again!

**Comment by mehalter** [comment]
@cobcobs  That's a good question, I will punt to @kabinspace since this is his project and definitely will have a certain vision as to how he wants the default look to be. I do personally like the look more than the current default and will be adding those changes to my config. I think the main goal for AstroVim is for heavy changes like this to be done easily and without much friction since everyone is going to want to sprinkle their own special sauce over their editor to fit their needs :D
