### ISSUE TITLE
Colorizer not work in Onedark theme.

### ISSUE THREAD

**Issue by datamonsterr** [kabinspace/AstroVim#149]
![image](https://user-images.githubusercontent.com/94211882/158039790-0b09637b-4b10-486c-8fec-5433be5f0808.png)
Edit: I still can't fix this issue, I guess it comes from treesitter. The screenshot I took is when I remove the colorizer.lua and install another plugins. With clorizer.lua, it just not works in every colorscheme even when I use :Clorizer.... commands. Anyone has the same problem?

**Comment by kabinspace** [comment]
@datamonsterr Does doing `ColorizerAttachToBuffer` or `ColorizerToggle` work?
