### ISSUE TITLE
Terminal toggles not working

### ISSUE THREAD

**Issue by thedandroid** [kabinspace/AstroVim#15]
None of the terminal toggles, i.e. lazygit, python, node, htop are working getting the following error:

`Error executing lua [string ":lua"]:1: attempt to call field '_HTOP_TOGGLE' (a nil value)`

**Comment by kabinspace** [comment]
@thedandroid These won't work unless you first open a normal terminal. For example: You should at least open the toggleterm once like this: `Ctrl` + `\` then you can close the terminal or keep it if you like and your lazygit, python, node and htop should be working fine, The reason of this is I have lazy-loaded toggleterm for faster startup time, it won't open unless you command It to. Snce the toggleterm is not loaded at first using those python,node etc commands gives an error. You can also solve this problem if you remove [this](https://github.com/kabinspace/AstroVim/blob/0fdf5b48ebfa2008cf60697db6cc3f2032b8b136/lua/core/plugins.lua#L286) line located in `lua/core/plugins.lua` file

**Comment by mehalter** [comment]
@thedandroid just a heads up I have a PR open that will resolve this issue and allow for the lazy loading to be enabled and these toglges work #241
