### ISSUE TITLE
A question about Custom LSP Server Settings

### ISSUE THREAD

**Issue by tinywaferShark** [kabinspace/AstroVim#156]
I used to use [svlang](https://github.com/imc-trading/svlangserver) which is a systemverilog LSP.
But it was not added in _nvim-lsp-installer_ ,I dont know how to add it in this config. Which text I should to read?  [add-custom-lsp-server-settings](https://github.com/kabinspace/AstroVim#add-custom-lsp-server-settings) or [Compley LSP server setup](https://github.com/kabinspace/AstroVim#compley-lsp-server-setup)

**Comment by hunger** [comment]
This language server is not known to the `nvim-lsp-installer` nor the `nvim-lspconfig` plugins? Then it gets tricky as nvim's LSP support has no idea what kind of files to load this language server for! In that case neither of the documentaion listed will help you:-/

https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md explains how to add a langauge server tot he nvim-lspconfig plugin... There was some documentation somewhere on how to add a langagueserver to lspconfig in an ad-hoc way somewhere, but I can't find that right now, sorry.

Once that is done the add-custom-lsp-server-settings approach should work.

**Comment by tinywaferShark** [comment]
Thanks very much. I think I know how to config the nvim-lspconfig. :)
