### ISSUE TITLE
packer.nvim: Error running config for telescope.nvim: ....?

### ISSUE THREAD

**Issue by datamonsterr** [kabinspace/AstroVim#161]
![2022-03-18-171859_1898x1020_scrot](https://user-images.githubusercontent.com/94211882/158986035-6ebc2031-8b17-4b56-bb42-ca95abfecc60.png)
I think my telescope still works fine after Enter to continue. But this error message keep appearing every first time I open astrovim. Is it a problem related to lazy loading stuffs? If anyone have any idea how to fix it pls help me. It's just annoying to see an error, everything still work perfectly fine.

**Comment by mehalter** [comment]
Could you take a look at #58. Some other people have run into this before and resolved it.

**Comment by datamonsterr** [comment]
@mehalter yeah, thanks
