### ISSUE TITLE
Neovim v0.7 Support

### ISSUE THREAD

**Issue by mehalter** [kabinspace/AstroVim#163]
This issue is just a placeholder for ongoing development discussion of Neovim v0.7 and getting AstroVim ready for it's release.

First things that come to mind:

- [x] migrate to Lua based autocommands
- [x] migrate to new keymap Lua API
- [x] global status line (`laststatus = 3`)
- [x] Lua based highlights. Purely Lua default theme

**Comment by mehalter** [comment]
@bryant-the-coder I know you expressed interest in helping out with this. I started this issue for discussion and made a branch for active development `nvim-0.7`

**Comment by bryant-the-coder** [comment]
- [x] global status line (`laststatus = 3`)

_migration to lua based autocommands need some time_

**Comment by mehalter** [comment]
lol have you tested any of these autocommands @bryant-the-coder ?

**Comment by mehalter** [comment]
@bryant-the-coder I just pushed a commit to fix the autocommands you did

**Comment by mehalter** [comment]
@bryant-the-coder also just adding `laststatus=3` didn't work. I think we are going to need to do more to fix that with lualine.

**Comment by bryant-the-coder** [comment]
> lol have you tested any of these autocommands @bryant-the-coder ?

FYI. the command astro update is not tested

**Comment by bryant-the-coder** [comment]
> @bryant-the-coder also just adding `laststatus=3` didn't work. I think we are going to need to do more to fix that with lualine.

u gitta find lualine kev for that

**Comment by mehalter** [comment]
@kabinspace just noticed 0.7 is also including a pure Lua highlight API so we should move the default theme to use this and remove the few vim script pieces there.

**Comment by mehalter** [comment]
I just made a commit that does this @kabinspace it does break our current backwards compatibility with 0.6 because it changes how the user interacts with highlights but it is significantly more straight forward
