### ISSUE TITLE
Open `nvim-tree` on startup

### ISSUE THREAD

**Issue by archiif** [kabinspace/AstroVim#164]
I'm trying to setup `nvim-tree` so that it opens on startup, but I can't get it to work. I also tried disabling lazy-loading for the nvim-tree plugin, but it still doesn't work.

This is my `init.lua`:

```lua
config = {
  plugins = {
    init = function(plugins)
      local my_plugins = {
        { "conweller/findr.vim" }
      }

      plugins["kyazdani42/nvim-tree.lua"]["cmd"] = nil

      return vim.tbl_deep_extend("force", plugins, my_plugins)
    end,

    ["nvim-tree"] = {
      open_on_setup = true,
    },  
  },
  polish = function()
    local opts = { noremap = true, silent = true }
    local map = vim.api.nvim_set_keymap
    local set = vim.opt

    set.relativenumber = true
    map("n", "<leader>ff", ":Findr<CR>", opts)
  end,
}

return config 
```

**Comment by mehalter** [comment]
This setup looks correct, but I'm away from my computer right now so I haven't tested directly. When you run `nvim` are you specifying a directory like `nvim .`? Without a directory it wouldn't run

**Comment by archiif** [comment]
I ran it by providing a file like this: `nvim file.txt`
I tried your command and it did open the tree, but is there no way to have this behaviour when opening a file?

**Comment by mehalter** [comment]
I don't believe so. I think you could achieve this with an autocommand to open the tree when opening a file buffer. But that is not what the open on startup option does for nvim-tree and they do not have a feature like this.
