### ISSUE TITLE
Virtual text appears despite having a diagnostics 'window'?

### ISSUE THREAD

**Issue by CleoMenezesJr** [kabinspace/AstroVim#166]
Sorry for the noob question, I just installed AstroVim for the first time and I was confused as to why this happens as it seems redundant to me and is there any way to disable the virtual text?
I've already tried to have the core/defaults.lua file and put virtual_text = false, but it still appears
![image](https://user-images.githubusercontent.com/54215258/159136135-fc912539-3942-4f21-abd2-1cbfca0de947.png)

**Comment by mehalter** [comment]
This can be disabled in your user settings in `user/unit.lua` with the field:

```lua
diagnostics = {
  virtual_text = false,
},
```

If you have not yet created a user settings file please check out the READNE for details

**Comment by CleoMenezesJr** [comment]
Sorry for the unnecessary ticket. Minutes after creating this ticket I saw that I was doing it wrong, I was pasting the user folder in the root.
Thanks for your patience in explaining.
