### ISSUE TITLE
Fresh install, not working snippets

### ISSUE THREAD

**Issue by RimuhRimu** [kabinspace/AstroVim#171]
i just installed AstroVim and thought that would work at the first, because I installed it a few days ago and worked great(also snippets did) but I didn't have time to configuring so switched to my previous config until i have time, but found troubles having no snippets when i installed it today

![image](https://user-images.githubusercontent.com/68438095/159175594-290c1301-2631-4476-883d-76440d1373dd.png)
![image](https://user-images.githubusercontent.com/68438095/159177108-e5261302-ff46-4e45-870c-fa8392cf1079.png)

**-Distro:** Linux Lite 5.6
**-nvim version:** 0.7
**-config:** didn't touch anything

i deleted `~/.local/share/nvim`
and backup my previous `~/.config/nvim/ `
installed AstroVim following instructions, installed tsserver

![image](https://user-images.githubusercontent.com/68438095/159175892-469db65e-f2c0-4829-95b0-e8718c2a3da9.png)
![image](https://user-images.githubusercontent.com/68438095/159175902-527fcdac-c1bf-4c22-8a63-b12239e3882f.png)

snippets for lua seems to work, but the rest don't

**Comment by mehalter** [comment]
Thanks for reporting @RimuhRimu it looks like some lazy loading we were trying to do is not working correctly. I have opened a PR to fix this issue.

**Comment by RimuhRimu** [comment]
I'm glad to help, thanks to you for fixing this, I already made the same changes in #172 so it now works, waiting for the update
