### ISSUE TITLE
Tabs aren't being aligned properly when doing split view

### ISSUE THREAD

**Issue by thisizkp** [kabinspace/AstroVim#177]
### Issue Type: Bug

Tabs aren't respecting split views (vertical). Refer to the screenshot. Right side view doesn't have any tab associated with it.
<img width="1792" alt="Screenshot 2022-03-22 at 4 37 11 PM" src="https://user-images.githubusercontent.com/4737336/159468433-9abacd0a-f165-44b6-8eb4-015219b8276a.png">

#### Steps to reproduce
1. Open a file
2. Search for a new file using `<leader>ff` and do `Ctrl V` to open the new file in split view

The more files we open, more it gets confusing and difficult to keep track of which tab is associated with which pane.

**Comment by kabinspace** [comment]
AstroVim uses a plugin called [bufferline.nvim](https://github.com/akinsho/bufferline.nvim). This is the normal behavior of the plugin. They currently don't support the feature of aligning with the splits. You can open an issue on a feature request on their repo for that.
