### ISSUE TITLE
Telescope file_ignore_patterns not applying

### ISSUE THREAD

**Issue by ErnieBernie10** [kabinspace/AstroVim#184]
Continuation of issue #146.

I have defined a Telescope override as described in the issue above:

```lua
plugins = {
  telescope = {
    defaults = {
      file_ignore_patterns = {
        ".git",
       -- all your ignore settings come here
        "**/node_modules/**",
      },
    },
  },
}
```

Expected result:

Files from node_modules don't show in Telescope search results

Actual result:

They do all show up

What am I doing wrong? I really like this vim configuration, this is the only hurdle I have encountered so far.

**Comment by mehalter** [comment]
I'm glad you are enjoying the configuration! I would take a look at this issue on  telescope's repository with the same issue: https://github.com/nvim-telescope/telescope.nvim/issues/522

Your syntax for the telescope override table looks correct, it seems to be related to the`node_modules` like and how it it written for Lua regex. You might just need to remove the slashes and `*`s

**Comment by ErnieBernie10** [comment]
I tried all the solutions in this thread you mentioned, still no success... The most liked solution from that thread didn't work either. This is what I have now.

```lua
telescope = {
      defaults = {
        file_ignore_patterns = {
          "node_modules",
        },
      },
    },
```

**Comment by mehalter** [comment]
Could you include your entire `init.lua` file so I can see it. I just tested it with just this as my `init.lua` and it worked:

```lua
return {
  plugins = {
    telescope = {
      defaults = {
        file_ignore_patterns = {
          "node_modules",
        },
      },
    },
  },
}
```

**Comment by mehalter** [comment]
Oh no, could you link to which part of the wiki you got it from @ErnieBernie10 so I can make sure that gets fixed. Sorry for the problem :(

**Comment by ErnieBernie10** [comment]
Well I tried the same config now with the telescope override and now it is working... I guess I must have had a character somewhere messing it up, but the config itself I think is fine. I'm talking about this file https://github.com/kabinspace/AstroVim/blob/main/lua/user_example/init.lua so you should be safe. 🙂
