### ISSUE TITLE
Fresh install sync fail

### ISSUE THREAD

**Issue by cheetosysst** [kabinspace/AstroVim#19]
Hi, I tried installing astrovim but end up with
![image](https://user-images.githubusercontent.com/32976729/152724560-8c7c038d-687a-4e90-98ed-eca58c665ff6.png)
There are multiple "not found" error before this but I didn't screenshot them.
I tried running PackerSync again
![image](https://user-images.githubusercontent.com/32976729/152724812-83847263-4bec-4c0c-987b-0cd1b9def471.png)

I follow the instructions, did I miss anything?

**Comment by kabinspace** [comment]
This looks like an installation fail from your side, Can you try running `:PackerInstall` once.

**Comment by cheetosysst** [comment]
![image](https://user-images.githubusercontent.com/32976729/152726100-c252256e-f7b8-4970-aae3-8a417f55b6c2.png)
`:PackerInstall`'s output

No, it happens on the first run, during "clone repository" `nvim +PackerSync`. I haven't manually install any plugin yet.

**Comment by kabinspace** [comment]
@cheetosysst Can you try doing reinstallation once

**Comment by cheetosysst** [comment]
There are a lot of not found errors :sweat_smile: , I think I saw one about "from vscode". Running PackerSync again doesn't show that error anymore.

Okay, should I delete the config folder and restart from there?

**Comment by kabinspace** [comment]
Yes, delete the nvim folder and clone the repository again.

**Comment by cheetosysst** [comment]
![image](https://user-images.githubusercontent.com/32976729/152726984-efea7d72-21ae-4d96-a081-f76ea264cbd3.png)
No error messages this time. Directly went from pulling plugins to this.

**Comment by kabinspace** [comment]
Are you on Linux or Windows?

**Comment by cheetosysst** [comment]
I'm on Endeavour OS (arch distro), neovim is installed through arch repo.

**Comment by kabinspace** [comment]
I've done a reinstallation from my side to see if AstroVim has to do anything with this but I'm afraid it's not. Since the plugins are failing to install/update from the packer plugin. Can you check if there are any issues that relate to your issue on their repo?

**Comment by cheetosysst** [comment]
I'm searching in packer's issues, and found this [https://github.com/wbthomason/packer.nvim/issues/381]( Failed to update #381 )
Is this a related issue?

**Comment by cheetosysst** [comment]
I followed the instruction in the comments [This](https://github.com/wbthomason/packer.nvim/issues/381#issuecomment-950027790)

However, git pull didn't fail and prints "Already up to date". git status showed doc/tags is untracked, but git stash didn't do anything, no local changes.

**Comment by kabinspace** [comment]
Did `git pull -rebase` work?

**Comment by cheetosysst** [comment]
Still `Already up to date` tho

**Comment by kabinspace** [comment]
But even after doing so, doing `:PackerUpdate` fails?

**Comment by cheetosysst** [comment]
I might have unintentionally made a stupid mistake.
I pressed CR and displayed the error messages. It says cannot resolve "github.com". After switching to my phone's carrier, every thing updates without error. So it is an issue on my side :sweat_smile:. Thank you for helping me! 

BTW, I noticed the github page for some plugins is now based on "main" branch, but it's still "master" on my side.
