### ISSUE TITLE
Fresh installation issues

### ISSUE THREAD

**Issue by buenjybar** [kabinspace/AstroVim#190]
I am having an installation problem 
 - NVIM v0.6.0

Once running the following command
```bash
nvim +PackerSync
```

nvim crash the first time with the following error message:

```bash 
Error detected while processing /home/ben/.config/nvim/init.lua:                                                                                                                                            
E5113: Error while calling lua chunk: .../site/pack/packer/start/impatient.nvim/lua/impatient.lua:73: Could not hash /home/ben/.config/nvim/lua/packer_compiled.lua                                         
stack traceback:                                                                                                                                                                                            
        [C]: in function 'error'                                                                                                                                                                            
        .../site/pack/packer/start/impatient.nvim/lua/impatient.lua:73: in function 'hash'                                                                                                                  
        .../site/pack/packer/start/impatient.nvim/lua/impatient.lua:255: in function 'load_from_cache'                                                                                                      
        .../site/pack/packer/start/impatient.nvim/lua/impatient.lua:275: in function 'loadfile'                                                                                                             
        /home/ben/.config/nvim/lua/core/utils.lua:94: in function 'compiled'                                                                                                                                
        /home/ben/.config/nvim/init.lua:33: in main chunk      
```

also, when I rerun the `nvim` command i have some troubles with some missing icons..

![image](https://user-images.githubusercontent.com/5807636/159744962-7e8c333c-5b62-4921-9684-556b1f73bd84.png)

Not sure both are related or not but i am a bit stuck.

Thank you, it is a great project :+1:

**Comment by mehalter** [comment]
@buenjybar are you coming from a previous neovim set up? Is there a chance you had some old stuff in your neovim `site` folder (on unix operating systems: `~/.local/share/nvim/site`) that is causing that first issue? If this may be the case I would recommend deleting that folder and starting the installation process from a clean environment.

With the icons, do you have a nerd font installed? This is required for the icons to work correctly

**Comment by buenjybar** [comment]
Thank you for the first tips,
I didn't know a previous version was installed.. so i skipped this step.
It is working fine now!


yes, I have a nerd font installed. but it seems not to be enough

**Comment by kabinspace** [comment]
@buenjybar What font are you using?

**Comment by kabinspace** [comment]
Also, can you try it with different nerd fonts like JetBrainsMono Nerd Font

**Comment by buenjybar** [comment]
> JetBrainsMono Nerd Font

This is the one i have installed

**Comment by buenjybar** [comment]
Ok my bad the terminal was using a different font by default :-1: 

Thank you for your help this is really helpful ! 
Working fine ! Gracias :pray:
