### ISSUE TITLE
fix: Python smartindent

### ISSUE THREAD

**Issue by AXGKl** [kabinspace/AstroVim#199]
Hi, 
thanks for the project. 

since `TSInstall python` is the example in the README: At least here this breaks smartindent with python, superannoying :-)

Seems I'm [not the only one](https://www.reddit.com/r/neovim/comments/l3mpiv/i_just_discovered_treesitter_was_the_reason_my/), took me a while to find out...

This fixes it:

![2022-03-25_](https://user-images.githubusercontent.com/9989548/160075061-1d9af995-96dc-4c30-9881-afc26728d4e8.png)

Not sure how widespread the problem really is but if it's present for you as well I'd suggest to put that into your default config. If not then possibly explain how to put the fix into the user/init.lua, for affected users like me.

Reproduce:

Install AstroVim -> `TSInstall python` -> `touch r.py` (so that TS is on at edit) -> `nvim r.py` -> `def foo():<CR>`. 

After the `<CR>` the cursor must be shifted and not be at column 0. Same with e.g. `while 1:<CR>`.

PS: Config:

Current stable neovim (as appimage), current Astrovim:

```bash
~/.config/nvim main !2 ?4 ❯ vi -v
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-780

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```

**Comment by mehalter** [comment]
Thansk for bringing this up! I looked in the treesitter docs and the indent feature is experimental at best so we are just going to disable it by default for all file types.
