### ISSUE TITLE
Changing colorscheme in user settings not working

### ISSUE THREAD

**Issue by jhwarner** [kabinspace/AstroVim#2]
Changing the colorscheme value in lua/user/settings.lua does not work. Adding plugins within that file does work, so I think the file is being picked up, just the colorscheme command isn't.

Changing the colorscheme manually works, so the colorscheme is installed. It will also work if I update the value in lua/core/defaults.lua

**Comment by kabinspace** [comment]
It looks like I made a mistake, I have just fixed it. Make sure you bring the following changes in lua/core/autcmds.lua file
https://github.com/kabinspace/AstroVim/commit/2bdf10e790301584dbc8f5fb6b806169d3c31685
