### ISSUE TITLE
(Windows) E492: Not an editor command: PackerSync

### ISSUE THREAD

**Issue by BryanRykowski** [kabinspace/AstroVim#20]
Trying to install AstroVim on Windows with NeoVim 0.6.1 and it appears packer is not installed. I saw a previous issue where the problem was an old NeoVim version in the Debian repos, but this is using the most recent stable version. I'm pretty sure I understand the install process because it worked for me on Debian.

**Comment by kabinspace** [comment]
@BryanRykowski I'm sorry but currently, AstroVim supports Linux only.

**Comment by BryanRykowski** [comment]
Understood 👍

**Comment by bryant-the-coder** [comment]
@BryanRykowski have u git clone packer?
