### ISSUE TITLE
Creating Code Snippets

### ISSUE THREAD

**Issue by Noxdor** [kabinspace/AstroVim#205]
Unfortunately I couldn't find the answer to this in the documentation, please point me in the right direction if I overlooked it.

How can I create Code Snippets in AstroVim/Lua/nvim? I switched a few weeks ago from VS Code and am not an expert with either yet, would highly appreciate if you could guide me in the right direction!

**Comment by AXGKl** [comment]
Hi,

I'm also a noob in AstroVim and it took me a while to figure it out - but with the setup below I'm happy.

**DISCLAIMER: I can't exclude that I worked around the framework at places!**

Goal: Do everything within your `user/init.lua` and not patch the framework.

## Pick a snippet engine

This is the program which can interpret your snips. I was using [Ultisnips][us] before and got it to
work but since they use **[luasnip][ls]**, I thought I give it a shot and from the docs it seems pretty
powerful, see below.

=> No need to add a plugin, already on board.

## Get some snippets

Took [these][fs], i.e. added

```lua
-- In user/init.lua:
    plugins = {
        init = {
                "rafamadriz/friendly-snippets",
                ... (your other non framework plugins)
        }, 
        -- other stuff
```
            
## Make the snippets show up in cmp


### cmp config

That's the completion tool, which offers the completions.

I want `<TAB>` completion and selection so again, in `user/init.lua`:

<details><summary>cmp setup</summary>

```lua

	plugins = {
		cmp = function(table)
			local cmp = require("cmp") -- lazy loaded -> requireable
			local luasnip = require("luasnip")
			local t = table.mapping
			local has_words_before = function()
				local line, col = unpack(vim.api.nvim_win_get_cursor(0))
				local lines = vim.api.nvim_buf_get_lines
				return col ~= 0 and lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
			end
			t["<Tab>"] = cmp.mapping(function(fallback)
				if cmp.visible() then
					cmp.select_next_item()
				elseif luasnip.expand_or_jumpable() then
					luasnip.expand_or_jump()
				elseif has_words_before() then
					cmp.complete()
				else
					fallback()
				end
			end, { "i", "s" })
			t["<S-Tab>"] = cmp.mapping(function(fallback)
				if cmp.visible() then
					cmp.select_prev_item()
				elseif luasnip.jumpable(-1) then
					luasnip.jump(-1)
				else
					fallback()
				end
			end, { "i", "s" })
			return table
		end,
		init = {...
        --other stuff
```

</details> 



### [null_ls][ns] config

[null_ls][ns] is the "hub" for any LSP action, including but not restricted to completion.

My config is this:

<details><summary>LSP setup</summary>

```lua
    ...
	-- Diagnostics configuration (for vim.diagnostics.config({}))
	diagnostics = { virtual_text = true, underline = true },

	-- null-ls configuration
	["null-ls"] = function()
		-- Formatting and linting
		-- https://github.com/jose-elias-alvarez/null-ls.nvim
		local status_ok, null_ls = pcall(require, "null-ls")
		if not status_ok then
			return
		end

		-- Check supported formatters
		-- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting

		-- Check supported linters
		-- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
		local b = null_ls.builtins
		local txt = { filetypes = { "markdown", "text" } }

		null_ls.setup({
			debug = true,
			sources = {
				-- https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md
				b.code_actions.refactoring,
				b.code_actions.shellcheck,
				b.completion.luasnip,    -- <------------- THIS IS THE ONE FOR LUASNIP
				b.completion.spell.with(txt),
				b.diagnostics.misspell.with(txt),
				b.diagnostics.shellcheck,
				b.diagnostics.write_good,
				b.formatting.black.with({ extra_args = { "--fast" } }),
				b.formatting.prettier.with({ filetypes = { "html", "json", "yaml" } }),
				b.formatting.shfmt,
				b.formatting.stylua,
				b.hover.dictionary.with(txt), -- shift-k is hover
			},
			-- NOTE: You can remove this on attach function to disable format on save
			-- on_attach = function(client)
			-- 	if client.resolved_capabilities.document_formatting then
			-- 		vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting()")
			-- 	end
			-- end,
		})
	end,

...
```

</details>

The important one for snippets is `b.completion.luasnip`. 

## Install

After a `nvim +PackerSync`, you should get the snippets offered.

GOTCHA: Cost me an hour to notice that to try, I needed to first touch a test file, only then open and test.
Because otherwise the LSP is not attached, overlooked that...

The friendly snippets will be here (at least on Linux) - see below how/where to add custom ones:

```

~ ❯ tree .local/share/nvim/site/pack/packer/start/friendly-snippets | head -n 10
.local/share/nvim/site/pack/packer/start/friendly-snippets
├── LICENSE
├── package.json
├── README.md
└── snippets
    ├── c.json
    ├── cobol
    │   ├── vscode_cobol-compound.json
    │   ├── vscode_cobol_dir.json
    │   ├── vscode_cobol_jcl.json
(...)

```

## Custom Snippets

You can go pretty sophisticated with luasnip's internal/vscode format but it also supports the good old
snipmate format, which is enough for my poor man's custom completion purposes. 

Within your `polish` function add this:

```lua
		require("luasnip.loaders.from_snipmate").lazy_load()
```

and add yours in here:

```
~/.config/nvim main ⇣3 !1 ?6 ❯ tree snippets
snippets
├── markdown.snippets
└── python.snippets

```

Note: To keep the framework repo clean and updateable but also to have my own stuff manageable in
*my* own dotfiles repo, I symlink my stuff from my `.config/nvim.personal` over into AstroVim, including
that snippets dir.


Gl - getting cmp and snippets to work was the hardest part in customizing everything.





[us]: https://github.com/SirVer/ultisnips
[ls]: https://github.com/L3MON4D3/LuaSnip
[fs]: https://github.com/rafamadriz/friendly-snippets
[ns]: https://github.com/jose-elias-alvarez/null-ls.nvim

**Comment by mehalter** [comment]
@AXGKl friendly-snippets is included in AstroVim and should work out of the box: https://github.com/kabinspace/AstroVim/blob/f683718f1293a7315971ebf9b4a02ba904a9ff37/lua/core/plugins.lua#L152-L156

**Comment by mehalter** [comment]
These are great notes @AXGKl ! Thank you for putting this together. (Just to note the existence of `friendly-snippets` in core AstroVim)

Also I think if you want to keep stuff in your `user/` folder you should be able to modify the lazy_load call to something like this:

```lua
require("luasnip.loaders.from_snipmate").lazy_load({ paths = { "./lua/user/snippets" } })
```

And then you can move your `snippets/` folder into your user directory :) Hopefully this can help build onto the great notes that you have already included!

**Comment by mehalter** [comment]
Also last thing is I'm not sure why you need the `luasnip` completion added to `null-ls`. Have you tried removing this? We have `luasnip` added as a `cmp` source in the code which is connecting luasnip to the completion engine. This _should_ work out of the box, if it isn't let me know:

https://github.com/kabinspace/AstroVim/blob/f683718f1293a7315971ebf9b4a02ba904a9ff37/lua/core/plugins.lua#L176-L183

**Comment by Noxdor** [comment]
I didn't expect such an extensive reply, thank you both a lot for the help! Today I'll take some time to look into it and get it running for myself.
Really appreciate the time you took, thank you!

**Comment by AXGKl** [comment]
Hi @mehalter,

muchas gracias for the further enlightenments. I address them all here (and adapted my write up above, accordingly).

> friendly-snippets is included in AstroVim

<details><summary>embarrassing...</summary>
Especially with the friendly Packer warning I got... I did first not realize that snippets completion is also via the LSP and was trying all the time by editing a **new** file, i.e. when the LSP was not attached => no snips in the completion.  
Then added it to my plugins, tried again, file was there => LSP attached -> working.

That in combination with a wrong configured ripgrep, and I did not see them within your sources...

Me: Ok, that was it, they leave it to the user which collection they want... - I think that's called cognitive bias, something which caused planes to crash... :stuck_out_tongue_winking_eye: 

Thanks again - I love small user configs!

</details>



> why you need the luasnip completion added to null-ls

Confirmed - the snips are offered also w/o that - nice & sorry.

Question to you:

So you already fully configured

- luasnips
- with friendly-snippets

to work out of the box. Also in your `cmp.lua` I see that you actually configure `<TAB>` completion - still, this does not work without all this in my user config: 

<details><summary>cmp setup</summary>

```lua
	plugins = {
		cmp = function(table)
			local cmp = require("cmp") -- lazy loaded -> requireable
			local luasnip = require("luasnip")
			local t = table.mapping
			local has_words_before = function()
				local line, col = unpack(vim.api.nvim_win_get_cursor(0))
				local lines = vim.api.nvim_buf_get_lines
				return col ~= 0 and lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
			end

			t["<Tab>"] = cmp.mapping(function(fallback)
				if cmp.visible() then
					cmp.select_next_item()
				elseif luasnip.expand_or_jumpable() then
					luasnip.expand_or_jump()
				elseif has_words_before() then
					cmp.complete()
				else
					fallback()
				end
			end, { "i", "s" })

			t["<S-Tab>"] = cmp.mapping(function(fallback)
				if cmp.visible() then
					cmp.select_prev_item()
				elseif luasnip.jumpable(-1) then
					luasnip.jump(-1)
				else
					fallback()
				end
			end, { "i", "s" })
			return table
		end,

````

</details>

Just tried again with a clean user config.

Adding this to your cmp.lua made it work:

```lua
      ["<Tab>"] = cmp.mapping(function(fallback)
        if cmp.visible() then
		cmp.select_next_item()
        elseif luasnip.expandable() then
```

Should that maybe in the *default config*, plus also the one for `S-Tab`? Then tab completion would work ootb.  
I'm not sure about the necessity of that `has_words_before function` in my config, took it from luasnips' docs, but `cmp.visible()` should be in, imho.

Lastly:

> if you want to keep stuff in your user/ folder 

I know it's possible with snippets specifically but I like the idea of having my super-sophisticated (*not*) stuff top level in my `$HOME/.config`. Also my old ftplugins needed to be in nvim dir anyway as it seems...

So I went the symlink route instead of nesting my stuff deep within a third party repo (yours) and it works and does not prevent updating astro.

<details><summary>.config tree</summary>

```
.config
├── nvim 
│   ├── .git  (astro vim, updateable)  
│   ├── colors
│   ├── ftplugin -> /home/gk/.config/nvim.personal/ftplugin
│   ├── lua
│            ├── user -> /home/gk/.config/nvim.personal
│   ├── screenshots
│   ├── snippets -> /home/gk/.config/nvim.personal/snippets
│   └── spell -> /home/gk/.config/nvim.personal/spell
├── nvim.personal
│    init.lua
│   ├── ftplugin
│   ├── snippets
│   ├── spell
````

</details>

**Comment by Noxdor** [comment]
@AXGKl Can confirm also for me tab completion doesn't work out of the box, I have to use the down arrow key and press enter for completion.

**Comment by Noxdor** [comment]
So a quick update how I made it work:

1. I added a `snippets` folder inside the `lua/user` directory
<details>
<summary>2. Inside the `snippets` folder I added a `package.json` file</summary>
<br>

```json
{
  "name": "personal snippets",
  "engines": {
    "vscode": "^1.11.0"
  },
  "contributes": {
    "snippets": [ 
      {
        "language": "vue",
        "path": "./vue.json"
      } 
    ]
  }
}
```

</details>

<details>
<summary>3. Inside the `snippets` folder I added a `vue.json` file for an example snippet to test (and use)</summary>
<br>

```json
{
  "setup": {
		"prefix": ["setup", "template"],
		"body": ["<template>",
				"\t$1",
				"</template>",
				"",
				"<script lang=\"ts\" setup>",
				"\t$2",
				"</script>",
				"",
				"<style lang=\"sass\">",
				"\t$3",
				"</style>",
				""
		],
		"description": "My standard setup Vue3 + TS"
	} 
}


```

</details>

<details>
<summary>4. Inside of nvim config root (`~/.config/nvim`), inside the `init.lua` file I added the line suggested by @mehalter (hope that is the right file)</summary>
<br>

```lua
-- Added by me
require("luasnip.loaders.from_vscode").lazy_load({ paths = { "./lua/user/snippets" } })
--
```

</details>

5. Enjoy the working snippet! Add more!

Hope this will be helping someone in the future. I think it would be great if this would be added to the project, like a boilerplate for new users to quickly set up their own snippets (best in a more generic way than mine, maybe so others can also with no config use snipmate snippets etc.), since it does take some time and effort right now to make it working (specially for a Lua & nvim nooby like me). It would definitely lower the threshold for new users to get started with nvim/astro-vim.

Cheers :)

**Comment by AXGKl** [comment]
> @AXGKl Can confirm also for me tab completion doesn't work out of the box, I have to use the down arrow key and press enter for completion.

Yep, I really think meanwhile it's a bug. I'll add an issue prbly, that big cmp config stanza  should not be required for standard tab complection.

PS: thanks for the 'real' guide ;-)

**Comment by mehalter** [comment]
@AXGKl please take a look at this PR from a while ago #120 basically the tab auto complete can cause issues with the navigation between locations within a snippet

**Comment by mehalter** [comment]
Also thanks so much @AXGKl and @Noxdor this is great user information and I'm planning on adding a cookbook/common config examples section to the wiki and this will be very useful for and entry in there!

**Comment by mehalter** [comment]
@AXGKl @Noxdor I have started working on the recipes page in the wiki. Just wanted to drop a link to the section on  custom VS Code snippets fully configured within the `user/` folder

**Comment by mehalter** [comment]
https://github.com/kabinspace/AstroVim/wiki/Configuration-Recipes#custom-vs-code-style-snippets

**Comment by Noxdor** [comment]
@mehalter Awesome, thank you for the link! Even better how you did it, so we can really just stay in the user folder and don't have to touch anything else :) Also, thanks to your comment I realised I missed the 1.0 release 😂 . Took me some moments to update, but I am really loving the things you guys changed! The pop ups are awesome but for the most I love the new git file look in the file explorer extension! It really bothered me that that X was on the left before making it look like I deleted the file 😝 

One thing I want to mention about the snippets: It didn't work for me without the `package.json` file I mentioned in my comment above - nvim gave me an error telling the plugin couln't find the snippets. So either I am doing something wrong, or if not you might want to add that to the documentation!

Anyway, awesome work with release 1.0, can't wait to see where this project will go!

**Comment by mehalter** [comment]
Glad you like the new updates! :D Hopefully AstroVim is coming together!

**Comment by machin3io** [comment]
Thank you so much for this!

**Comment by machin3io** [comment]
> So a quick update how I made it work:
> 
>     1. I added a `snippets` folder inside the `lua/user` directory
> 
> 
> 2. Inside the `snippets` folder I added a `package.json` file
> 3. Inside the `snippets` folder I added a `vue.json` file for an example snippet to test (and use)
> 4. Inside of nvim config root (`~/.config/nvim`), inside the `init.lua` file I added the line suggested by @mehalter (hope that is the right file)
> 
>     5. Enjoy the working snippet! Add more!
> 
> 
> Hope this will be helping someone in the future. I think it would be great if this would be added to the project, like a boilerplate for new users to quickly set up their own snippets (best in a more generic way than mine, maybe so others can also with no config use snipmate snippets etc.), since it does take some time and effort right now to make it working (specially for a Lua & nvim nooby like me). It would definitely lower the threshold for new users to get started with nvim/astro-vim.
> 
> Cheers :)

Thank you so much for this!

**Comment by machin3io** [comment]
> @AXGKl please take a look at this PR from a while ago #120 basically the tab auto complete can cause issues with the navigation between locations within a snippet if the CMP is open and you _don't_ want to use the CMP option but want to navigate the next snippet location the user would need to recognize this and do a binding to close the menu before navigating to the next location in the snippet

I've added an <A-Tab> mapping specifically for this to only jump. Wondering if there is a better suggested approach though?

`          ["<A-Tab>"] = cmp.mapping(function(fallback)
            if luasnip.jumpable(1) then
              luasnip.jump(1)
            else
              fallback()
            end
          end, { "i", "s" }),
`

**Comment by akiranguyenvni** [comment]
Hi guys,
I did follow the guidance doc of @mehalter  and recommendation of @Noxdor but it couldn't work for typescript.
My steps:
1. add folder "snippets" into "lua/user"
2. add package.json with content:
`{
  "name": "user-snippets",
  "engines": {
    "vscode": "^1.11.0"
  },
  "contributes": {
    "snippets": [
      {
        "language": "typescript,typescriptreact",
        "path": "./typescript.json"
      }
    ]
  }
}
`
4. add typescript.json with content:
`{
  "Something": {
    "prefix": "smt",
    "body": ["const { ${1:name} } = this.props"]
  }
}
`
6. add lazy load of luasnip in both user/init.lua and root/init.lua but none of them work.
`
        require("luasnip.loaders.from_vscode").lazy_load()
        require("luasnip.loaders.from_vscode").lazy_load { paths = { "./lua/user/snippets" } } -- load snippets paths
        require("luasnip.loaders.from_vscode").lazy_load { paths = { "./snippets" } } -- load snippets paths
`

It took me days to try but nothing work.
Could you guys pleased tell me where I'm wrong? How to solve it?
Thanks!

**Comment by mehalter** [comment]
@akiranguyenvni I just tested with your code, there seems to be some bugs I think. Here is a working example ([Custom Snippets Documentation](https://astronvim.com/Recipes/snippets)):

### 1 Load the Snippets

If you are using `user/init.lua` file for your plugins table, this is an example `user/init.lua` file:

```lua
return {
  plugins = {
    {
      "L3MON4D3/LuaSnip",
      config = function(plugin, opts)
        require "plugins.configs.luasnip"(plugin, opts) -- include the default astronvim config that calls the setup call
        require("luasnip.loaders.from_vscode").lazy_load { paths = { "./lua/user/snippets" } } -- load snippets paths
      end,
    },
  },
}
```

If you have a `user/plugins/` folder then you need to put this in that folder with a file like `user/plugins/luasnip.lua` (If you have a `user/plugins/` folder this will take precedence over your `user/init.lua` file's `plugins` table):

```lua
return {
  "L3MON4D3/LuaSnip",
  config = function(plugin, opts)
    require "plugins.configs.luasnip"(plugin, opts) -- include the default astronvim config that calls the setup call
    require("luasnip.loaders.from_vscode").lazy_load { paths = { "./lua/user/snippets" } } -- load snippets paths
  end,
}
```

### 2 Define the snippets

Here is a `user/snippets/package.json`:

```json
{
  "name": "user snippets",
  "engines": {
    "vscode": "^1.11.0"
  },
  "contributes": {
    "snippets": [
      {
        "language": [
          "typescript",
          "typescriptreact"
        ],
        "path": "./typescript.json"
      }
    ]
  }
}
```

Here is a `user/snippets/typescript.json`:

```json
{
  "Something": {
    "prefix": "smt",
    "body": ["const { ${1:name} } = this.props"]
  }
}
```

![2023-05-01_11:51:21_screenshot](https://user-images.githubusercontent.com/1591837/235482323-f0346077-1cea-4993-a98d-8ace8c31fad2.png)

**Comment by akiranguyenvni** [comment]
Worked like a charm! Thank @mehalter ~

I got it. Bcz I have a folder named "plugins" for bunch of things, hence the LuaSnip in `user/init.lua` not work.
I have to make another file `luasnip.lua` to lazyload the snippets.
Comprehend it now. Thanks!

**Comment by h1tarth** [comment]
i am unable to find any user/ dir , is what we have to create  in nvim  dir  "**plz explain the file tree**"

**Comment by mehalter** [comment]
@h1tarth here is a link to the documentation: https://astronvim.com/Configuration/manage_user_config

**Comment by Tyrn** [comment]
I'm really sorry. The snippets work out of the box, indeed. There are screenshots, here and in [the docs](https://github.com/rafamadriz/friendly-snippets). My newbie trouble is that I can't figure out how to use the snippet parameters :) . What key(s) should I press after the initial <tab>, when I see a beautiful template? Probably it's so obvious that nobody's dwelling on that. Not so obvious for me, unfortunately :)
