### ISSUE TITLE
Which font(s)?

### ISSUE THREAD

**Issue by mrinterweb** [kabinspace/AstroVim#21]
I see that there is a requirement for nerdfonts to be installed, but when I went to the website it had multiple fonts available. Do I need to install all fonts provided on the website or is there a particular font?

**Comment by kabinspace** [comment]
You can choose any fonts from that site, the font shown in the preview image of AstroVim is called JetBrains Mono Nerd Font.

**Comment by mrinterweb** [comment]
Thanks. I found that I could set the font for my GUI editor with:

```
vim.api.nvim_exec([[set guifont=JetBrainsMono\ Nerd\ Font\ Mono:h15]], false)
```
After installing it with `brew install --cask font-jetbrains-mono-nerd-font`

It wasn't clear to me that I needed a patched version of the font in order for it to include all the symbols. I was using JetBrains Mono as my font already, so I was confused. It has been helpful learning about nerdfonts. 
Thanks for the help
