### ISSUE TITLE
Highlighting line or words under cursor not working with custom extension

### ISSUE THREAD

**Issue by flamendless** [kabinspace/AstroVim#212]
Im using custom file extension `lua2p` (similar to lua with more tokens) and handles syntax highlighting with this in my `settings.lua`
```lua
require("filetype").setup({
	overrides = {
		function_extensions = {
			lua = function()
				vim.bo.filetype = "lua"
				require("user.love").SetLove()
			end,
			lua2p = function()
				require("user.love").SetLua2p()
			end
		}
	},
})
```
`SetLua2p` is this:
```lua
function Love.SetLua2p()
	vim.cmd[[set syntax=lua]]
	vim.bo.commentstring = "--%s"
	vim.cmd[[syn match luaFunc "self"]]
	vim.cmd[[syn match luaOperator "\:"]]
	vim.cmd[[syn match luaOperator "\."]]
	vim.cmd[[syn match luaOperator "\["]]
	vim.cmd[[syn match luaOperator "\]"]]
	vim.cmd[[syn match luaOperator "("]]
	vim.cmd[[syn match luaOperator ")"]]
	vim.cmd[[syn match luaOperator ","]]
	vim.cmd[[syn match luaComment "!"]]
	vim.cmd[[syn match luaComment "@"]]
	vim.cmd[[syn match luaStatement "love.[a-z]*.[a-zA-Z]*"]]
end
```

Note that i cant just treat lua2p as lua because the lsp for lua breaks for lua2p because of the added tokens.

How can i make highlighting line or words under cursor with custom extension? Thanks

**Comment by mehalter** [comment]
I am not sure the correct vim/lua to achieve what you are describing sadly. I did however realize that we didn't expose the `filetype` plugin to be easily extended so I opened this PR #237  so instead of needing to do the entire requires with `filetype` you can just put the new table in `plugins.filetype` in the `init.lua`

**Comment by flamendless** [comment]
The problem with using a custom filetype/extension haha. Anyway, thank you!
