### ISSUE TITLE
Issue with Telescope fuzzy finder

### ISSUE THREAD

**Issue by Kindlewing** [kabinspace/AstroVim#215]
![Screenshot from 2022-03-27 11-34-14](https://user-images.githubusercontent.com/28827961/160289002-b26244a4-2df8-48dd-869b-9181220d8e2b.png)

When I first start up nvim, I get this error when I search. It goes away right after, and doesn't show up for the rest of the session, but on startup it appears.

**Comment by mehalter** [comment]
Please check #58 some other people have had this issue as well. Looks like uninstalling and reinstalling the `fzf-native` plugins solved it. The plugin sometimes messes up it's own installation it looks like
