### ISSUE TITLE
Issue with fuzzy finder

### ISSUE THREAD

**Issue by Kindlewing** [kabinspace/AstroVim#216]
When I start up AstroVim, I get the following error:
![Screenshot from 2022-03-27 11-34-14](https://user-images.githubusercontent.com/28827961/160291230-896d0aba-806e-4b76-8652-a91af4a05507.png)
 
It goes away right after I search something and stays that way for the rest of the session, but on startup, this error appears.

**Comment by mehalter** [comment]
Please check https://github.com/kabinspace/AstroVim/issues/58 some other people have had this issue as well. Looks like uninstalling and reinstalling the fzf-native plugins solved it. The plugin sometimes messes up it's own installation it looks like
