### ISSUE TITLE
[Question] Install astrovim with user config correctly?

### ISSUE THREAD

**Issue by Gavus** [kabinspace/AstroVim#217]
This is the process I need to do in order to install astrovim with my user config.

1. Clone astrovim to ~/.config/nvim.
2. Run nvim +PackerSync.
3. Run nvim +PackerSync again (for my plugins).
4. Edit colorscheme to my preference.

Is it possible to run PackerSync once and install my plugins?
If I set my colorscheme first before doing PackerSync I get multiple errors, how can I get past this?

Im using the default config and have only changed the colorscheme row, and added plugins.

**Comment by mehalter** [comment]
If your `user` folder is present then `nvim +PackerSync` should work. For the colorscheme, you can set up your `user/init.lua` similar to the following to get better error handling:

```lua
local colorscheme = "default_theme"
local colorscheme_avail, _ = pcall(require, "your_colorscheme_package")
if colorscheme_avail then
  colorscheme = "your_colorscheme"
end

local config = {

  -- Set colorscheme
  colorscheme = colorscheme,
}

return config
```

You will need to adjust the `your_colorscheme_package` and `your_colorscheme` to match your set up. But this will check if your colorscheme is available, if it isn't then it will just use the `default_theme`. Once you have this colorscheme change then you should be able to just clone the repo, set up your `user/` folder and then do `nvim +PackerSync` once and get everything set up including your plugins

**Comment by Gavus** [comment]
Thank you, it works great!

**Comment by bihari123** [comment]
i want to :set wrap and :set norelativenumber permanantly. Any tips?

**Comment by Rafael-Conde** [comment]
> i want to :set wrap and :set norelativenumber permanantly. Any tips?

for future reference:

in `user/init.lua` :
```lua
local config = {
  -- your previous configs...
  options = function(local_vim)
    local_vim.opt.relativenumber = false
    local_vim.opt.wrap = true
    return local_vim
  end,
  -- your next configs...
}
```

**Comment by Akhilbisht798** [comment]
okay so i has been quite a time. How can i do this now?
