### ISSUE TITLE
Feature request: Add plugin to detect indentation style

### ISSUE THREAD

**Issue by Rot127** [kabinspace/AstroVim#218]
Some projects differ in their indentation style (tab vs. spaces). IDEs like vscode detect this and auto indent the code accordingly.
AstroVim does not yet unfortunately.

Would it be possible to add a plugin which does this?
Maybe https://github.com/tpope/vim-sleuth

What do you think?

**Comment by mehalter** [comment]
We have looked into this a bit and have not yet decided if this is worth including in the base install. This is luckily easy to do with the built in user config system in your `init.lua`:

```lua
return {
  plugins = {
    init = {
      { "tpope/vim-sleuth" },
    },
  },
}
```
