### ISSUE TITLE
Onedark default colorscheme

### ISSUE THREAD

**Issue by kden416** [kabinspace/AstroVim#219]
Can i change default onedark colorscheme to another onedark colortheme?

How to disable default onedark?

**Comment by AXGKl** [comment]
I think Astro's theme is just based on OneDark but there are small differences.

Means: You can additionally install it like other plugins, i.e. in `user/init.lua`:

```lua
init = {
            "joshdick/onedark.vim",
            (...)
```	

and then configure it like described in [onedark's repo](https://github.com/joshdick/onedark.vim).

You enable it by saying `colorscheme = "onedark"` on top of `user/init.lua` or set it in the polish function.

**Comment by mehalter** [comment]
@AXGKl has also described this here: https://github.com/kabinspace/AstroVim/issues/221#issuecomment-1081514218 I'm going to close this because of duplicate
