### ISSUE TITLE
Missing the full percentage in the status bar

### ISSUE THREAD

**Issue by red-elka** [kabinspace/AstroVim#22]
i don't know why it's not showing the percentage and other stuff in the status bar
![Screenshot AstroVim](https://user-images.githubusercontent.com/95357302/152783602-341bd65c-43a5-40b8-9dd2-99026bcf661b.png)

**Comment by kabinspace** [comment]
@red-elka Have you tried this with different fonts? Some fonts might cause this problem.

**Comment by kabinspace** [comment]
Can you clarify what you mean by it's not showing other stuff?

**Comment by red-elka** [comment]
> Can you clarify what you mean by it's not showing other stuff?

like that yellow square and some other icons or script in the status bar are overlapping

**Comment by kabinspace** [comment]
Can you check if there's an issue that relates to your problem in lualine's repository? The best advice from my side would be to try a different font.

**Comment by kabinspace** [comment]
@red-elka Did doing any of that help you?

**Comment by red-elka** [comment]
> Can you check if there's an issue that relates to your problem in lualine's repository? The best advice from my side would be to try a different font.

What is the font that you are using?

**Comment by kabinspace** [comment]
@red-elka I'm using JetBrainMono Nerd Font

**Comment by red-elka** [comment]
yes i works great with it

**Comment by red-elka** [comment]
one last question please,
i'm new to lua and i want to convert the configuration below to lua in atrovim, any idea how can i do it?
```
noremap ; l
noremap l j
noremap j h
```

**Comment by kabinspace** [comment]
Since the issue about the specific topic is resolved, I'm going the close the issue, can you clarify more about your last question? It seems like you are trying to map these keys but there's no clear hint on what exactly

**Comment by red-elka** [comment]
@kabinspace i want to convert this vim config to lua

**Comment by bryant-the-coder** [comment]
yes yes it is like that
