### ISSUE TITLE
Help on changing theme

### ISSUE THREAD

**Issue by krshrimali** [kabinspace/AstroVim#221]
Hi, thank you for helping with sharing AstroVim with the community! 🎉 

I'm trying to change the theme and referred the closed issues where it was discussed. I'm in the main branch, and things aren't working. Here is what I tried so far:

Filename: `lua/core/defaults.lua`

```lua
local config = {

  -- colorscheme = "default_theme",
  colorscheme = "catppuccin",
 
  plugins = {
    { "catppuccin/nvim", as = "catppuccin" },
    packer = {
      compile_path = vim.fn.stdpath "config" .. "/lua/packer_compiled.lua",
    },
  },

  -- ...
```

After this, I did: `PackerInstall` - no pop up showed up, but I waited for a few seconds, and tried opening nvim again. Got this error:

![image](https://user-images.githubusercontent.com/19997320/160541362-0c098b38-3482-4faf-a1af-263942571e20.png)

Probably the plugin wasn't installed, but...not sure how to fix this. Can someone please help? Thank you!

**Comment by Gavus** [comment]
I was stuck with the same problem yesterday. @mehalter have provided an answer for this issue in https://github.com/kabinspace/AstroVim/issues/217.

**Comment by AXGKl** [comment]
Hi, imho you should not touch anything outside your `lua/user` folder but use the config machinery astrovim provides:

1. copy the `lua/user_example` folder to `lua/user` if not done so yet.
2. in `lua/user/init.vim` add:

```lua
   plugins = {
		init = {
			"catppuccin/nvim",
	(...)
```
3. nvim +PackerSync -> you'll see it downloaded and installed
4. configure:

```lua
local config = {
	-- Set colorscheme
	--colorscheme = "default_theme",
	colorscheme = "catppuccin",
```

PS: Nice colorscheme, love it ;-)

**Comment by krshrimali** [comment]
Thank you so much, @Gavus and @AXGKl - it works!! Yep, love the colorscheme too ❤️ Closing this issue, and really appreciate the help! 🚀

**Comment by flamendless** [comment]
I'll just add here to avoid creating a new issue. Using `"eddyekofo94/gruvbox-flat.nvim"` How can i use this along with the new setup?
```lua
vim.o.background = "dark"
vim.g.gruvbox_flat_style = "hard"
```
Previously this works but now, putting this in the `polish` function doesn't change the theme.

**Comment by mehalter** [comment]
@flamendless these settings probably need to be set before the colorscheme is loaded. This should go in the where you add the plugin in the `plugin.init` table with an entry that looks like:

```lua
{
  "eddyekofo94/gruvbox-flat.nvim",
  config = function()
    vim.o.background = "dark"
    vim.g.gruvbox_flat_style = "hard"
  end,
}
```

And then you will need to do a `:PackerSync` call to apply these config changes

**Comment by flamendless** [comment]
> @flamendless these settings probably need to be set before the colorscheme is loaded. This should go in the where you add the plugin in the `plugin.init` table with an entry that looks like:
> 
> ```lua
> {
>   "eddyekofo94/gruvbox-flat.nvim",
>   config = function()
>     vim.o.background = "dark"
>     vim.g.gruvbox_flat_style = "hard"
>   end,
> }
> ```
> 
> And then you will need to do a `:PackerSync` call to apply these config changes

Tried that. Didn't work, i still get the same colorscheme for some reason

**Comment by zxlvera** [comment]
Adding further questions to this issue, how do we add theme configurations in user/init.lua?
Where can we add theme configs inside `local config` ?
```
local catppuccin = require("catppuccin")

-- configure it
catppuccin.setup(<settings>)
```

This was my attempt as I was unsure where to place the theme config.
```
plugins = {
    -- Add plugins, the packer syntax without the "use"
    init = {
      { "catppuccin/nvim", as = "catppuccin", 
        setup = function()
              return styles = {
              comments = "italic",
              functions = "italic",
              keywords = "italic",
              strings = "NONE",
              variables = "italic",
            },
      end,
      },
.... other code ....
}
```

**Comment by liyongxing1410** [comment]
Hi i was following your recommend but i'm stucking with this issue. 

![image](https://user-images.githubusercontent.com/89700043/177142009-41147da9-45e9-4e74-9f74-fe24189ed623.png)

**Comment by krshrimali** [comment]
@liyongxing1410 - Can you please explain more about what you are trying to do? Mainly these questions:

1. Are you trying to install a new theme?
2. What files did you change? [also please share the changes]
3. Your neovim version
4. Did you do `nvim +PackerSync`?

**Comment by liyongxing1410** [comment]
@krshrimali, Hi!
I changed the user/init.lua and set the colorscheme follow "onehalf" theme. I'm using the latest version ownr neovim from brew with --HEAD and i also sync packer/

**Comment by krshrimali** [comment]
@liyongxing1410 - Can you please share your `user/init.lua` file content here?

**Comment by HungLe14** [comment]
@krshrimali i think i add the init in the wrong plugins function. By the way it is running as normal but the new colorscheme doesn't applied.

![image](https://user-images.githubusercontent.com/99705956/177144072-9ef3bae8-87d5-4817-affb-bc69fc88c803.png)
![image](https://user-images.githubusercontent.com/99705956/177144100-7c69e1e3-9cff-4e73-81a3-3211501b68b3.png)

**Comment by liyongxing1410** [comment]
@krshrimali i think i added the init in the wrong plugins function. By the way it is running as normal but the new colorscheme doesn't applied.

![image](https://user-images.githubusercontent.com/99705956/177144072-9ef3bae8-87d5-4817-affb-bc69fc88c803.png)
![image](https://user-images.githubusercontent.com/99705956/177144100-7c69e1e3-9cff-4e73-81a3-3211501b68b3.png)

**Comment by krshrimali** [comment]
> @krshrimali i think i added the init in the wrong plugins function. By the way it is running as normal but the new colorscheme doesn't applied.
> 
> ![image](https://user-images.githubusercontent.com/99705956/177144072-9ef3bae8-87d5-4817-affb-bc69fc88c803.png) ![image](https://user-images.githubusercontent.com/99705956/177144100-7c69e1e3-9cff-4e73-81a3-3211501b68b3.png)

Looks like a plugin issue, maybe try this:

```
init = {
    {
        "sonph/onehalf",
        config = function() vim.cmd("colorscheme onehalflight") end
    },
    -- rest of your config
}
```

**Comment by liyongxing1410** [comment]
@krshrimali  I think it should be the issue from onehalf theme. Thank you for you help!

**Comment by mehalter** [comment]
@liyongxing1410 this also could be breaking changes in Neovim nightly. AstroNvim does *not* officially supported nightly Neovim. I would recommend you using Neovim stable.

**Comment by gmankab** [comment]
> And then you will need to do a `:PackerSync` call to apply these config changes

@mehalter, astronvim switched from packer to lazy.nvim

how can i do it now?
