### ISSUE TITLE
Is it possible to modify dashboard config through user settings?

### ISSUE THREAD

**Issue by firatakandere** [kabinspace/AstroVim#228]
Hi,
I'm trying to change dashboard's configuration via lua/user/init.lua, it seems the dashboard configuration is stored in global variables:
https://github.com/kabinspace/AstroVim/blob/main/lua/configs/dashboard.lua

and re-defining in users/init.lua does not have any effect (my wild guess is it's executed before dashboard's config?)

I noticed some plugin configurations are using 'user_plugin_opts' functions to fetch user config, I was thinking to implement similar functionality for dashboard's config but wanted to verify first that there's not an effective way yet.

**Comment by mehalter** [comment]
Where are you putting the calls? You should be able to put them in the `polish` function in your `user/init.lua` to guarantee that they happen after the dashboard config is happening

**Comment by mehalter** [comment]
@firatakandere I found the error in ordering that causes the discrepancy. I have opened a PR to fix this. Then putting the global overrides in the `polish` function will work as intended!

**Comment by mehalter** [comment]
@firatakandere this fix should be available now with `:AstroUpdate`

**Comment by firatakandere** [comment]
@mehalter Thanks, but unless I'm missing something, it is still the same.
I pulled the last commit already.
Here's my user/init.lua:

```
local config = {
  polish = function() {
    local g = nvim.g
    g.dashboard_custom_header = { " " }
  end,
}

-- powerline does not support nvim
vim.g.powerline_loaded = 1
vim.g.airline_powerline_fonts = 1

return config
```

**Comment by firatakandere** [comment]
Any possibility that the values are already consumed in utils.compiled(), therefore overriding them after it's called is useless?

**Comment by mehalter** [comment]
@firatakandere sorry for the late reply, not sure how I missed this. You have a typo in the provided config. It should be `local g = vim.g`.

**Comment by firatakandere** [comment]
@mehalter Nice catch! Yep, it does work now, thanks a lot!

**Comment by mehalter** [comment]
@firatakandere @Korokoukousei We just pushed a change to AstroNvim to move from Dashboard.nvim to Alpha.nvim since Dashboard hasn't been updated in over a year and seems to be relatively dead at this point. This does come with a much nicer approach to changing the header on the Dashboard. This can now be done with the `header` field in the `user/init.lua` file. Here is an example with the default header:

```lua
return {
  header = {
    " ",
    " ",
    " ",
    " ",
    " ",
    " █████  ███████ ████████ ██████   ██████",
    "██   ██ ██         ██    ██   ██ ██    ██",
    "███████ ███████    ██    ██████  ██    ██",
    "██   ██      ██    ██    ██   ██ ██    ██",
    "██   ██ ███████    ██    ██   ██  ██████",
    " ",
    "    ███    ██ ██    ██ ██ ███    ███",
    "    ████   ██ ██    ██ ██ ████  ████",
    "    ██ ██  ██ ██    ██ ██ ██ ████ ██",
    "    ██  ██ ██  ██  ██  ██ ██  ██  ██",
    "    ██   ████   ████   ██ ██      ██",
    " ",
    " ",
    " ",
  },
}
```
