### ISSUE TITLE
Error executing lua

### ISSUE THREAD

**Issue by meanindra** [kabinspace/AstroVim#23]
I am getting this error when I try to run `:NvimTreeToggle` or when I use `Space+e` .
But this error show only first time.
```shell
E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim
/lua/packer/load.lua:83: Vim(lua):E5108: Error executing lua ...vim/site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree.lua:128: attempt to index field 'Tree' (a nil value)
stack traceback:
        [C]: in function 'cmd'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
```
![Screenshot from 2022-02-07 18-43-19](https://user-images.githubusercontent.com/36324543/152794825-e7defe0b-050b-4ff1-944e-a287de791019.png)

**Comment by kabinspace** [comment]
@meanindra This issue has been occurring since yesterday and it is found that it's actually coming from the plugin itself, have you tried refreshing neovim and trying again? Most of them got solved after opening and closing the nvim tree a few times. If that didn't help then let me know.

**Comment by kabinspace** [comment]
The author has mentioned that he is making some changes in the repo which may cause some unstability so until that moment you can replace [this](https://github.com/kabinspace/AstroVim/blob/main/lua/core/plugins.lua#L74-L81) with the given code down below
```lua
    use {
      "kyazdani42/nvim-tree.lua",
      cmd = "NvimTreeToggle",
      commit = "8b27fd4",
      config = function()
        require("configs.nvim-tree").config()
      end,
      disable = not config.enabled.nvim_tree,
    }
 ```

**Comment by meanindra** [comment]
> Most of them got solved after opening and closing the nvim tree a few times

I've tried it and it works, but it's bit annoying, when first time I try to open NvimTree and error comes up

**Comment by kabinspace** [comment]
@meanindra The code given above should completely get rid of the error when you open nvim-tree. It will roll back to the version where the plugin was stable.
