### ISSUE TITLE
Having issues in select mode.

### ISSUE THREAD

**Issue by Rid1-fz-06** [kabinspace/AstroVim#230]
In select mode,(as first charecter) pressing p is pasting from clipboard(like visual mode) and pressing space is not inserting any space. Can you please check this problem? It's not letting use snippets properly.

**Comment by mehalter** [comment]
could you give a workflow description of this in more detailed like keybindings to get into select mode, etc. just so I can try to recreate the issue you are describing?

**Comment by Rid1-fz-06** [comment]
In my last configuration I haven't changed anything yet. I have three TS grammers installed (python, c and lua) and one LSP server installed (pyright). I first encountered this problem with snippets. After expanding any snippet (__main__ snippent of python for example)

the position of my cursor is | and current mode is select (pass charecter sequence is selected)

if __name__ == '__main__':
    p|ass

now if I try to use the print function and hit the 'p' charecter, instead of putting 'p' charecter it pastes something from clipboard.

**Comment by mehalter** [comment]
Ah I have found this issue in the config

https://github.com/kabinspace/AstroVim/blob/851a52fc19c6239916cfd9e46a2d613fb1a2dcc5/lua/core/mappings.lua#L164

I will patch this first thing in the morning. Sorry!
