### ISSUE TITLE
Add Recipes/Cookbook Section to Wiki

### ISSUE THREAD

**Issue by mehalter** [kabinspace/AstroVim#239]
We should add a Recipes/Cookbook section to the wiki with  answers to common user configuration questions. This would also be a good location to highlight some advanced Astrovim user configuration repositories that might be a good reference to users looking to do some significant modifications to the base installation.

**Comment by AXGKl** [comment]
Maybe you can add a stanza about **unattended install** (`nvim  --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'`) into the set of recipes.


<details><summary>Rationale</summary>

AV addresses, imho, two groups of people:

1. The rather beginners in vim and/or lua, coming from other IDEs
2. Not so beginners in vim, which could / did before hack all the plugins together also w/o Astro - BUT they like the idea of having a lot of dev-must-have config within a "standard" framework.
Where people can be pointed to, to learn it and only the really personal stuff left in theirs. That's far more agreeable, project or company wide, than a full vim config of one specific person.

Unattended installs, i.e. the possibility to throw editor install steps into a server setup script or playbook, is totally irrelevant for group 1 but very relevant for 2. 



</details>

**Comment by mehalter** [comment]
Added: https://github.com/kabinspace/AstroVim/wiki/Configuration-Recipes
