### ISSUE TITLE
Overwrite default plugin configs

### ISSUE THREAD

**Issue by ExarGD** [kabinspace/AstroVim#24]
Is there a way to overwrite default plugin settings properly?
I wanted to change a color scheme and found out that lualine colors are hardcoded. So to change those settings I need to either edit `/configs/lualine.lua` or add my custom config file in `user` folder and then change the line on [L88](https://github.com/kabinspace/AstroVim/blob/main/lua/core/plugins.lua#L88) in `/core/plugins.lua`.
What am I missing?

**Comment by kabinspace** [comment]
@ExarGD Currently, you can't overwrite default plugins that comes with AstroVim from user settings alone. You have to make a direct change in the core and configs.
