### ISSUE TITLE
[Question] window to view compiler errors and warnings?

### ISSUE THREAD

**Issue by Kindlewing** [kabinspace/AstroVim#245]
![Screenshot from 2022-03-31 15-37-18](https://user-images.githubusercontent.com/28827961/161135570-da1a4be1-ab6e-45bf-8bfd-bab408f948e4.png)

In the case of an error going off the screen, because they are at the end of the line, if the line itself is short, I can't advance the cursor to view the error.

Is there a keybinding to view the errors or warnings in the current file in their entirety?

**Comment by mehalter** [comment]
You can do a few options:

`<leader>lD` to view all the diagnostics in telescope

Or you can go to a specific line with a diagnostic message and do either `gl` or `go` in normal mode to read the entire diagnostic message on that line

**Comment by mehalter** [comment]
These are all documented in the wiki page for default keybindings: https://github.com/kabinspace/AstroVim/wiki/Default-Mappings#lsp-mappings

**Comment by Kindlewing** [comment]
Thank you!
