### ISSUE TITLE
vim . does not open netrw nor nerdtree

### ISSUE THREAD

**Issue by MrEverymorning** [kabinspace/AstroVim#25]
Temporary work around is to go to lua/core/utils.lua  and comment out lines 10 -12 that disable netrw

**Comment by bryant-the-coder** [comment]
astrovim has nvimtree and not nerdtree

**Comment by kabinspace** [comment]
@MrEverymorning can you clarify your problem a little more?

**Comment by mehalter** [comment]
@MrEverymorning I ran into this and it is because `nvim-tree` is not being loaded on start up, it's lazy loaded. If you comment out this line: https://github.com/kabinspace/AstroVim/blob/97509bd29e3f60a77cc2f0944fd4b76ed954e10e/lua/core/plugins.lua#L76 then it should start working as you expect it.

**Comment by kabinspace** [comment]
@mehalter doing that might cause few problems, I would rather suggest you to do [this](https://github.com/kabinspace/AstroVim/issues/23#issuecomment-1031474570) instead

**Comment by mehalter** [comment]
@kabinspace  Is the link you put solving the issue mentioned? It seems that even with the other commit the plugin wouldn't be running until the toggle keybinding is run and so it wouldn't start automatically when opening neovim with something like `neovim .`

**Comment by mehalter** [comment]
@MrEverymorning also the vim history is because the Shaba file is being set to none so you can comment out the Shaba line to get back history. I did this for telescope oldfiles to work correctly instead of just the current session's history

**Comment by kabinspace** [comment]
> @kabinspace Is the link you put solving the issue mentioned? It seems that even with the other commit the plugin wouldn't be loaded until the toggle keybinding is run and so it wouldn't start automatically when opening neovim with something like `neovim .`

Yes, it won't open automatically at the start because it is lazy-loaded, which means it will only load when user commands it to. It is done to decrease the startup time of neovim

**Comment by kabinspace** [comment]
> @MrEverymorning also the vim history is because the Shada file is being set to none so you can comment out the Shada line to get back history. I did this for telescope oldfiles to work correctly instead of just the current session's history
> 
> https://github.com/kabinspace/AstroVim/blob/97509bd29e3f60a77cc2f0944fd4b76ed954e10e/lua/core/utils.lua#L34

Yes, I've disabled some of the default plugins that come with neovim to once again speed up the startup time and make the neovim more faster and snappy. You can manually enable them if you really find them useful.

**Comment by kabinspace** [comment]
@MrEverymorning Is your problem solved?
