### ISSUE TITLE
`E492: Not an editor command` when using command a second time

### ISSUE THREAD

**Issue by nschloe** [kabinspace/AstroVim#258]
Using the default leader commands, e.g., `<space>ff`, it all works fine the first time. When trying it a second time, however, I'm getting
```
E492: Not an editor command: Telescope find_files
```

**Comment by mehalter** [comment]
I cannot replicate this behavior in a clean installation of AstroVim. Could you share your user configuration (`user/init.lua`) to see if it could be coming from there?

**Comment by nschloe** [comment]
My installation is also clean. I don't have a `~/.config/nvim/user/` directory. Where else should I look?

**Comment by mehalter** [comment]
Are you only getting this behavior with Telescope bindings? After your do `<space>ff` the first time and it starts saying "Not an editor command". Could you try running `:Telescope find_files` and see if that works?

Also when it stops working could you send the output of `:PackerStatus`?

**Comment by nschloe** [comment]
> Could you try running :Telescope find_files and see if that works?

I can run `:Telescope find_files` once. When I try it the second time, I get the original error.

Here's my `:PackerStatus`:

```
                     packer.nvim - Total plugins: 43
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 • Comment.nvim
 • FixCursorHold.nvim
 • LuaSnip
 • SchemaStore.nvim
 • better-escape.nvim
 • bufferline.nvim
 • cmp-buffer
 • cmp-nvim-lsp
 • cmp-path
 • cmp_luasnip
 • dashboard-nvim
 • filetype.nvim
 • friendly-snippets
 • gitsigns.nvim
 • impatient.nvim
 • indent-blankline.nvim
 • indent-o-matic
 • lualine.nvim
 • neo-tree.nvim (not loaded)
 • neoscroll.nvim
 • nui.nvim (not loaded)
 • null-ls.nvim
 • nvim-autopairs
 • nvim-cmp
 • nvim-colorizer.lua
 • nvim-lsp-installer
 • nvim-lspconfig
 • nvim-notify
 • nvim-toggleterm.lua (not loaded)
 • nvim-treesitter
 • nvim-ts-autotag
 • nvim-ts-context-commentstring
 • nvim-ts-rainbow
 • nvim-web-devicons
 • packer.nvim
 • plenary.nvim
 • popup.nvim
 • smart-splits.nvim (not loaded)
 • symbols-outline.nvim (not loaded)
 • telescope-fzf-native.nvim
 • telescope.nvim
 • vim-bbye
 • which-key.nvim
```

Any logs that I could check?

**Comment by mehalter** [comment]
It would also probably help to make sure you don't have any dangling old files. Could you delete your `~/.local/share/nvim/site` folder before running those commands and force Packer to reinstall your plugins?

**Comment by nschloe** [comment]
Yup! Wiping
```
~/.local/share/nvim/site
```
and reinstallting all packer modules via
```
:PackerCompile
:PackerSync
```
did the trick. Thanks!
