### ISSUE TITLE
loop or previous error loading module luasnip.config

### ISSUE THREAD

**Issue by adam-hanna** [kabinspace/AstroVim#26]
Starting `nvim` and I get the following error:

```
Error detected while processing /home/ahanna/.local/share/nvim/site/pack/packer/start/LuaSnip/plugin/luasnip.vim:                                                      
line   44:
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'luasnip.config'
stack traceback:
[C]: in function 'require' [string ":lua"]:1: in main chunk
```

**Comment by bryant-the-coder** [comment]
send your conf? i dont think there is luasnip.vim

**Comment by srRyo** [comment]
> Starting `nvim` and I get the following error:
> 
> ```
> Error detected while processing /home/ahanna/.local/share/nvim/site/pack/packer/start/LuaSnip/plugin/luasnip.vim:                                                      
> line   44:
> E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'luasnip.config'
> stack traceback:
> [C]: in function 'require' [string ":lua"]:1: in main chunk
> ```

I could try this:
```
rm -rf $HOME/.local/share/nvim
rm -rf $HOME/.cache/nvim
```
With the above, you will delete the cache and downloaded plugins (your settings will not be lost).
When opening AstroVim, run `:PackerSync` to reinstall the plugins.

I hope this can solve your problem and sorry for my bad english.

**Comment by adam-hanna** [comment]
@srRyo 

No worries at all, your english is great! :)

> I could try this:
> 
> ```
> rm -rf $HOME/.local/share/nvim
> rm -rf $HOME/.cache/nvim
> ```

That worked, thanks!
