### ISSUE TITLE
Error loading LSP handlers

### ISSUE THREAD

**Issue by andradei** [kabinspace/AstroVim#262]
After installing some LSP servers, starting `nvim` gives error:

```
packer.nvim: Error running config for nvim-lspconfig: ~/.config/nvim/lua/configs/lsp/init.lua:7: attempt to index a boolean value
```

and

```
packer.nvim: Error running config for nvim-lspconfig: ~/.config/nvim/lua/configs/lsp/lsp-installer.lua:10: attempt to index a boolean value
```

I think both of them seem to be related to requiring "configs.lsp.handlers".

Here's a video:

https://user-images.githubusercontent.com/2653546/162324900-6297987f-5bc7-44d7-b2a6-cc50b24021ab.mp4

**Comment by mehalter** [comment]
I haven't seen this in particular.

Could you try doing a `:PackerSync` and see if the issue persists?

If that doesn't fix it, could check your nvim folder and see what commit of the repo you are currently on? After getting that information could you try doing a `: Astroupdate` to see if a newer version has addressed this.

**Comment by mehalter** [comment]
Also have you made any changes to the source code or added anything in your user configuration? It seems like it would probably be related to the `on_attach` function

**Comment by andradei** [comment]
I have ran all of those commands before, then I posted this issue and stopped using `nvim` altogether until now.
And the issue is gone 🤷‍♂️
