### ISSUE TITLE
Some errors about lsp-installer lua script

### ISSUE THREAD

**Issue by spacepetunia** [kabinspace/AstroVim#269]
![1](https://user-images.githubusercontent.com/61891966/162548594-621d4c0f-7895-4926-971f-ce29fd5a4394.png)

After installing AstroVim config and launch it, I recieve some errors about attemption to index a boolean value. But installing seems OK (I install clangd and its works well)

Can you check?

**Comment by mehalter** [comment]
Can you try to run a `:PackerSync` and see if the issue still persists?

**Comment by mehalter** [comment]
Another user had this issue (#262) and it was fixed with a packer sync

**Comment by mafakheri** [comment]
hi. i have the same problem
i use last version of neovim 
and try checkhealth .
is give some warning and i install every thing on that.
then i use :PackerSync but still problem exist.
![Screenshot from 2022-04-09 16-53-22](https://user-images.githubusercontent.com/100694455/162574119-55d7cca0-570d-4b75-9b04-81efa16aedaf.png)

**Comment by mehalter** [comment]
@mafakheri is this after a fresh installation on AstroVim? This could come from lingerie stuff for some reason in your vim files.

Could you try running

```
rm -r ~/.local/share/nvim/site
rm -r ~/.cache/nvim
nvim +PackerSync
```

And see if that resolves it?

**Comment by mafakheri** [comment]
still i get same error.
it's maybe because of my neovim version.
i will try remove my neovim and try by version 0.6 .

**Comment by mehalter** [comment]
Ah are you using a version of neovim <0.6?

**Comment by mafakheri** [comment]
no im last version of neovim (0.7 some thing)
i change that to 0.6 but not work .
im try install all dependeny again . perhaps problem is there

**Comment by mehalter** [comment]
Ah interesting, I just did a series of clean installations and one of them caused the issue for a second but then it went away. Does the issue continuously happen? Or just once on the initial installation?

**Comment by mehalter** [comment]
Everything should be working with nvim 0.7 im also using that version as well

**Comment by mehalter** [comment]
@spacepetunia are you also running neovim 0.7 nightly and does the issue persist regularly or just initially when installing and then goes away?

**Comment by datamonsterr** [comment]
@mafakheri @spacepetunia Have you tried commentting out the lspconfig line in the core/plugins.lua and re-enable it again? This simply reinstall the lspconfig and it did work for me. 
```lua
  -- Built-in LSP
  {
    "neovim/nvim-lspconfig",
    event = "BufWinEnter",
    config = function()
      require "configs.lsp"
    end,
  },

``` 
(line 222 lua/core/plugins.lua)
Note: commentting out --> Save file (Astrovim will packersync for you automatically) --> re-enable it ---> Save file ---> Done

**Comment by botbench** [comment]
I am seeing these errors also, after I did an AstroUpdate. I am using nvim 0.6.1. I see these errors even with a totally clean install. I nuked .local/share/nvim and .config/nvim, to not avail.

**Comment by mafakheri** [comment]
> @mafakheri @spacepetunia Have you tried commentting out the lspconfig line in the core/plugins.lua and re-enable it again? This simply reinstall the lspconfig and it did work for me.
> 
> ```lua
>   -- Built-in LSP
>   {
>     "neovim/nvim-lspconfig",
>     event = "BufWinEnter",
>     config = function()
>       require "configs.lsp"
>     end,
>   },
> ```
> 
> (line 222 lua/core/plugins.lua) Note: commentting out --> Save file (Astrovim will packersync for you automatically) --> re-enable it ---> Save file ---> Done

i think what you said work. but i handly run PackerSync. tnx

**Comment by mafakheri** [comment]
> Ah interesting, I just did a series of clean installations and one of them caused the issue for a second but then it went away. Does the issue continuously happen? Or just once on the initial installation?

my problem solved. but when i had problem the error show every time i open nvim
NOTE: when i had error, lsp work fine.(i hope you can understand what i'm saying . my english is weak)

**Comment by botbench** [comment]
I just went through all the commits since the end of March, and checked them out, one by one. It all goes pear-shaped after commit f1d960d7e33a5c1adf3eba0d9c4a3b25f6fdbc1a.

Last good commit (for me) is:
```
commit f1d960d7e33a5c1adf3eba0d9c4a3b25f6fdbc1a
Merge: 6ecf191 d86979b
Author: Micah Halter <micah@balena.io>
Date:   Wed Apr 6 10:50:05 2022 -0400

    Merge pull request #259 from kabinspace/window_focus_fix

    Fix focusing on window pop up
```

**Comment by mehalter** [comment]
Thanks for investigating @botbench ! I will look into why this messed it up!

**Comment by mehalter** [comment]
@botbench thanks so much for that pointer! I was able to identify the bug. It has actually been something that has been around forever but some recent lazy loading improvements have exposed it haha #272 should fix it!
