### ISSUE TITLE
how to change background color and other colors

### ISSUE THREAD

**Issue by csilent-c0d3r** [kabinspace/AstroVim#270]
hi i want to change the background color but i don't know how?

**Comment by mehalter** [comment]
This can be done in the `user/init.lua` file. The following is an example of a minimal complete `user/init.lua`:

```lua
return {
  default_theme = {
    colors = {
        bg = "#1e222a",
    },
  },
}
```

And you replace the hex code with the color you want. In this table you can override any of the colors defined in the following file: https://github.com/kabinspace/AstroVim/blob/main/lua/default_theme/colors.lua

**Comment by mehalter** [comment]
More examples of overriding the default theme details can be seen here: #169

**Comment by csilent-c0d3r** [comment]
tnx sir
i need to color with opcity but i don't know how .

**Comment by mehalter** [comment]
I'm not sure that there is color opacity in neovim. These override locations give you full access to rewriting the colors and the highlight groups so anything possible in vim highlighting is possible to do from there if that can help guide your investigation
