### ISSUE TITLE
Allow out-of-tree location for user config

### ISSUE THREAD

**Issue by tomKPZ** [kabinspace/AstroVim#276]
I manage my `$HOME` directory using `git` and I have `.config/nvim` as a submodule pointing to the AstroVim repo.  The default location for the user config is `~/.config/nvim/lua/user`, however this is problematic because

- I can't manage my AstroVim config from my `$HOME` repo
- My `$HOME` repo will detect that there's changes in `.config/nvim`

The first problem may be solved with a symlink, but that requires a manual step after checking out my `$HOME` repo, and doesn't solve the second problem.

I'm requesting that AstroVim look for user config in an alternative location (eg `~/.config/astrovim`) as an alternative to the current location (`~/.config/nvim/lua/user`).

**Comment by mehalter** [comment]
@tomKPZ thanks for reaching out! I have started taking a look at this and have put together an initial attempt at this. This does require the user config location to be in `~/.config/astrovim/lua/user` since we are just adding the folder to the `runtimepath` and that's where Neovim will look for modules

**Comment by mehalter** [comment]
Please take a look at #278 and let me know if that is what you are looking for!

**Comment by tomKPZ** [comment]
Thanks!  I checkout out the `alt_config` branch and can confirm that addresses the issue for me!

Will the path change from `~/.config/astrovim` to `~/.config/astronvim` once the rebranding is complete?

**Comment by mehalter** [comment]
Yeah there would be a change to `astronvim` once the rebranding is done. We could also just change it now since it's a feature so close to the rebranding and people adopting this wouldn't want to need to migrate.

**Comment by tomKPZ** [comment]
Ok, sounds good to me.  Please feel free to land you change as-is.  `mv ~/.config/astrovim ~/.config/astronvim` is not a large chore :)

**Comment by mehalter** [comment]
Awesome, I'll go ahead and merge this over and get it on main
