### ISSUE TITLE
lazygit not work

### ISSUE THREAD

**Issue by lifesign** [kabinspace/AstroVim#28]
i have lazygit installed on my mac, but when i run <Space> + g + g, got below error

```
E5108: Error executing lua [string ":lua"]:1: attempt to call global '_LAZYGIT_TOGGLE' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

**Comment by srRyo** [comment]
@lifesign I fixed this by removing this line in "core/plugins.lua"

https://github.com/kabinspace/AstroVim/blob/97509bd29e3f60a77cc2f0944fd4b76ed954e10e/lua/core/plugins.lua#L286

then run `:PackerSync` and with this it should work :)

**Comment by kabinspace** [comment]
@lifesign This has been already addressed [here](https://github.com/kabinspace/AstroVim/issues/15#issuecomment-1030742915)

**Comment by lifesign** [comment]
got it. thx
