### ISSUE TITLE
returnin of plugins-table from e.g. user/plugins/init.lua

### ISSUE THREAD

**Issue by kraxli** [kabinspace/AstroVim#280]
Many thanks for this great nvim-configuration!

Brief question as I am struggling with the logic of some `user/` configuration files. For
example the file `user/plugins/init.lua`. Following exactly your example

```lua
return {
  { "andweeb/presence.nvim" },
}
```
works as expected. However the following version of the `user/plugins/init.lua` does not work:
```lua
local my_plugins = {
  { "andweeb/presence.nvim" },
}
return my_plugins
```
Why is the second version not working?

**Comment by mehalter** [comment]
You misspelled `local`

**Comment by kraxli** [comment]
sorry the misspelling is only in the message not in my code.

**Comment by mehalter** [comment]
I'm not sure why that wouldn't be working. I just did testing with the following `user/plugins/init.lua` file with clean AstroVim installation:

```lua
local my_plugins = {
  { "andweeb/presence.nvim"},
}

return my_plugins
```

I think just making sure you don't have any syntax errors or anything in your file.

**Comment by mehalter** [comment]
@kraxli are you still encountering this?

**Comment by mehalter** [comment]
I am going to go ahead and close this since this doesn't seem to relate to AstroVim and is a base `lua` related bug/syntax error somewhere in the user configuration files.

**Comment by Naintre-Jad** [comment]
hi, i don't understand where i must put "return plugins"
