### ISSUE TITLE
LSP is shown as inactive

### ISSUE THREAD

**Issue by Javets70** [kabinspace/AstroVim#281]
I've tried looking into lsp.log but I didnt find anything which would point out what the real issue is
It just stopped working suddenly 2 days back.
(vim newbie here)

**Comment by mehalter** [comment]
@Javets70 I would take a look at the default settings for whatever LSP server you are using here: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md

The `root_dir` setting is how the LSP server is started automatically by checking for the existence of some files. Like having a `package.json` file for starting the typescript server.

**Comment by mehalter** [comment]
@Javets70 were you able to resolve this issue?

**Comment by Javets70** [comment]
@mehalter I looked into the config for pyright and I believe it works for any file but still I have the same error.

Also i tried installing lunarvim because at first I thought it was an issue with config but I encountered the same problem in lunarvim too.

Sorry to keep you waiting.

**Comment by mehalter** [comment]
@Javets70 pyright looks for the following files (https://github.com/neovim/nvim-lspconfig/blob/fd7843ad04cbc8ee2181bed9c3e83839b0d0b285/lua/lspconfig/server_configurations/pyright.lua#L10):


```lua
local root_files = {
  'pyproject.toml',
  'setup.py',
  'setup.cfg',
  'requirements.txt',
  'Pipfile',
  'pyrightconfig.json',
}
```

**Comment by Javets70** [comment]
@mehalter Ahh , It used to work before for individual files , how do I make it like that.

Thanks for your quick support.

**Comment by mehalter** [comment]
Do you have any sort of custom config for the `pyright` server? It should be set by default to do `single_file_support = true,` but if it isn't starting automatically it seems like that might be set to false. Do you have a repository with your `user/` folder available anywhere and I could take a look more closely? (maybe selfish but I am glad it happened with lunarvim too so it doesn't seem to be an AstroVim problem 😂 )

**Comment by Javets70** [comment]
@mehalter I havent made any changes to the pyright server config , I dont even know how lua works.

Sorry I dont have any repo like that on my github.

**Comment by kabinspace** [comment]
I'm going to close this issue as this specific problem seems like more of a lsp related issue instead of AstorVim itself.. I recommend you to open this issue on their [repo](https://github.com/neovim/nvim-lspconfig) for a better chance of getting this solved. I would also encourage you to drop the solution in case you got the issue solved :)
