### ISSUE TITLE
color scheme

### ISSUE THREAD

**Issue by mafakheri** [kabinspace/AstroVim#282]
hello
if i wanna use another color schem like :
https://github.com/tjdevries/gruvbuddy.nvim
what should i do ?
i try set colorscheme = "lua require('colorbuddy').colorscheme('gruvbuddy')"
and i get error
then i delete lua but still get error
if you have time explan this to me
sorry for silly Question from me :)

**Comment by mehalter** [comment]
instead of using the `colorscheme` field here because of how `gruvbuddy` works you just need to put this in your `plugins.init` table:

```lua
    {
      "tjdevries/gruvbuddy.nvim",
      config = function()
        require("colorbuddy").colorscheme "gruvbuddy"
      end,
      requires = "tjdevries/colorbuddy.vim",
    },
```
