### ISSUE TITLE
Cannot set editor options `user/init.lua`

### ISSUE THREAD

**Issue by victor-timofei** [kabinspace/AstroVim#285]
Setting editor options inside my `~/.config/nvim/lua/user/init.lua` has no effect.

I am trying to enable the Treesitter folds.

When I do this in `~/.config/nvim/init.lua` it works as expected.

```lua
vim.o.foldmethod = 'expr'
vim.o.foldexpr = 'nvim_treesitter#foldexpr()'
```

I know that `user/init.lua` is used to configure the plugins, but I want to keep the root `init.lua` clean and not have to resolve conflicts on each merge.

**Comment by mehalter** [comment]
Where are you putting these options? Are you putting them in your `polish()` function? I use these options in my `polish()` function in my `init.lua`:

```lua
vim.opt.foldmethod = 'expr'
vim.opt.foldexpr = 'nvim_treesitter#foldexpr()'
```

**Comment by victor-timofei** [comment]
I completely missed that function. It works like a charm.

Thanks 😄

**Comment by kraxli** [comment]
folding doesn't work for me even putting the two options in my `polish()` function or any other potential place:
```
    vim.opt.foldmethod = 'expr'
    vim.opt.foldexpr = 'nvim_treesitter#foldexpr()'
```

**Comment by mehalter** [comment]
@kraxli do you have treesitter running for the files that you are using?

**Comment by kraxli** [comment]
kind of looks like. Running `checkhealth` and e.g. for `python`

```
vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for python: ABI version 13
```

**Comment by mehalter** [comment]
@kraxli once you open the file could you check the output of 

`:lua print(vim.opt.foldexpr._value)` and `:lua print(vim.opt.foldmethod._value)`?

**Comment by kraxli** [comment]
ah thanks! I had `nvim.treesitter#foldexpr()` instread of `nvim_treesitter#foldexpr()`. Sorry!

**Comment by marcoSolano** [comment]
I had the same issue, for some reason which-key.nvim was setting it up manual by default..

**Comment by Mate2xo** [comment]
How did you solve the issue @marcoSolano ? Having the same issue here, but neither setting the options through `user/options.lua` nor in the `user/init.lua` `#polish` function actually set the desired fold options (`foldlevel`, `foldlevelstart`, `foldmethod`, `foldexpr`). I even had a try on directly modifying the `astronvim/options.lua` (default for `foldlevel` is `99`, but that didn't work either.
