### ISSUE TITLE
How do I change neo-tree's position to the right side

### ISSUE THREAD

**Issue by andradei** [kabinspace/AstroVim#288]
I tried changing it via `lua/user/init.lua` but no changes take effect, including its position.

It works when I change it in the neo-tree's setup function directly from the AstroVim config, but it will get overridden in future updates.

Looking at neo-tree's documentation, looks to me that there's no other way.

But I'm hoping to be wrong. How would I do it via `lua/user/init.lua`?

**Comment by eqr** [comment]
@andradei I have the same problem. Did you try to change other configs in user/init.lua? It seems they are not respected at all.

**Comment by kabinspace** [comment]
@andradei That's the incorrect way to override configs for plugins. The correct method is to first create a `plugins` folder inside `user` directory and then create a file for the plugin that you want to override, in this case we are overriding settings for neo-tree plugin so we would create a file called `neo-tree.lua` (same file name as default config file) inside `user/plugins` and then inside the file is where we would want to put our override settings, in this case we want to make the file tree appear at the right side, so for that we would want to put the following:
```lua
return {
  window = {
    position = "right",
  },
}
```
For more information about configuration I would recommend you to checkout the [documentation](https://astronvim.github.io/)

**Comment by mehalter** [comment]
This can also go directly inside of your `user/init.lua` file like this:

```lua
return {
  plugins = {
    ["neo-tree"] = {
      window = {
        position= "right",
      },
    },
  },
}
```

**Comment by andradei** [comment]
@kabinspace That works! This new documentation (at least I didn't see before) if much better than the Wiki as far as plugin configuration goes.

Thank you.

**Comment by andradei** [comment]
@kabinspace @mehalter So my issue was that I was using `neo_tree` as the plugin "key" instead of `neo-tree` which needs to be wrapped like so: ["neo-tree"].

The `user_example/init.lua` example has `neo_tree` there so I thought the plugin for renamed internally or something.

Thank you guys.

**Comment by mehalter** [comment]
https://astronvim.github.io/configuration/plugin_defaults#neo-tree

https://astronvim.github.io/configuration/config_options

I would just make sure that you are referring to the documentation for the configuration options for the keys for the `plugins` table

**Comment by andradei** [comment]
Yes, the `enabled` table, I used it as a reference for plugin names.
The new documentation helps a ton.

**Comment by mehalter** [comment]
Yeah, that `enabled` table doesn't actually apply to all of the plugins either. Just the ones that are shown in the `user_example` so it's not a very good reference for the `plugins` table. Sorry for the confusion!

**Comment by woss** [comment]
> https://astronvim.github.io/configuration/plugin_defaults#neo-tree
> 
> https://astronvim.github.io/configuration/config_options
> 
> I would just make sure that you are referring to the documentation for the configuration options for the keys for the `plugins` table

these links are broken

**Comment by woss** [comment]
Latest v3 way.


```lua
return {
  "nvim-neo-tree/neo-tree.nvim",
  as = "neo-tree",
  config = function()
    require("neo-tree").setup {
      window = {
        position = "right",
      },
    }
  end,
}
```

**Comment by mehalter** [comment]
@woss that is incorrect, this is actually removing all of the setup in neo-tree that AstroNvim does. I would recommend not doing it that way and using the `opts` table

**Comment by woss** [comment]
@mehalter thanks for the comment, i found this somewhere on Astrovim discord so I added it and worked.

Is this correct way to do it?

```lua
-- plugins/neo-tree.lua
return {
  "nvim-neo-tree/neo-tree.nvim",
  opts = {
    window = {
      position = "right",
    },
  },
}
```

**Comment by mehalter** [comment]
Yup @woss looks perfect!
