### ISSUE TITLE
update pre-requisites in readme

### ISSUE THREAD

**Issue by Rakesh-rules** [kabinspace/AstroVim#289]
Hi,

Thanks for this amazing repo. I recently installed Astro vim and been enjoying it rather than configuring it myself 👍🏼 .

I did find some pain points for nvim newbie like myself on Readme. Kindly include optional installation of fzf and lazygit as pre-requisites. Hope It would be helpful for people starting with this repo 🤞.

**Comment by mehalter** [comment]
Thanks for the feedback, I have opened a PR to add all of these optional requirements along with their default keybindings/explanations of provided functionality.
