### ISSUE TITLE
lsp formatting not working

### ISSUE THREAD

**Issue by Rakesh-rules** [kabinspace/AstroVim#290]
I have followed readme and installed tssever for Lsp and JS,TS and TSX for Treesitter. I could see the lsp servers getting attached but formatting isn't working when I save the file or using `<leader>lf`. No sure need to add anything to user config, haven't added anything there yet.

P.S: Forgive if I made anything silly 😓.

![image](https://user-images.githubusercontent.com/24510595/163540456-bc72246a-cdcd-4c18-9e31-1c044378ae33.png)

**Comment by kabinspace** [comment]
You would need to install a formatter for that specific language. AstorVim uses [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) for formatting. We have disabled some of the default formattings that comes with the lsp server as they conflict with the null-ls formatting. I would suggest you to install a formatter for your desired language. For example: You can install a formatter for HTML & javascript like prettier using npm like this: `npm install -g prettier`
After that you would need to define your installed formatter name [here](https://github.com/kabinspace/AstroVim/blob/ae8fe46d5854c2dc9ebb3192328aa6ea6a80e976/lua/user_example/init.lua#L136) like this
`formatting.prettier,`
