### ISSUE TITLE
Change neoscroll speed

### ISSUE THREAD

**Issue by step4** [kabinspace/AstroVim#295]
Hi,

I'm fairly new to neovim and wanted to test AstroVim to get some batteries included.

I would like to change the scrolling speed of the neoscroll plugin and after reading the plugin documentation, I think you have to override the default keymap somehow.

I'm am not sure how I can set these inside the `user/init.lua` file?

Can someone point me to the right direction?

**Comment by mehalter** [comment]
It looks like neoscroll doesn't have a super friendly interface for modifying the speed. There are 2 places to change this one is setting the speed in the mapping definitions and the other thing you can modify is the `easing_function` in the setup. Both of these can be done in the `user/init.lua` file. For the mappings there is a helper function in neoscroll for making setting these easier which would go perfectly in the `polish()` function which simply is run at the very end of your config. The `easing_function` is part of the `neoscroll.setup()` call which can be done in the plugin configuration section of the `init.lua`.

Here is a full `user/init.lua` example that simply changes the easing_function of neoscroll and sets up different bindings with non-default speeds and different functions for each:

```lua
return {
  plugins = {
    neoscroll = {
      easing_function = "quadratic",
    },
  },

  polish = function()
    local neoscroll_avail, neoscroll_config = pcall(require, "neoscroll.config")

    if neoscroll_avail then
      neoscroll_config.set_mappings {
        -- Syntax: t[keys] = {function, {function arguments}}
        -- Use the "sine" easing function
        ["<C-u>"] = { "scroll", { "-vim.wo.scroll", "true", "350", [['sine']] } },
        ["<C-d>"] = { "scroll", { "vim.wo.scroll", "true", "350", [['sine']] } },
        -- Use the "circular" easing function
        ["<C-b>"] = { "scroll", { "-vim.api.nvim_win_get_height(0)", "true", "500", [['circular']] } },
        ["<C-f>"] = { "scroll", { "vim.api.nvim_win_get_height(0)", "true", "500", [['circular']] } },
        -- Pass "nil" to disable the easing animation (constant scrolling speed)
        ["<C-y>"] = { "scroll", { "-0.10", "false", "100", nil } },
        ["<C-e>"] = { "scroll", { "0.10", "false", "100", nil } },
        -- When no easing function is provided the default easing function (in this case "quadratic") will be used
        ["zt"] = { "zt", { "300" } },
        ["zz"] = { "zz", { "300" } },
        ["zb"] = { "zb", { "300" } },
      }
    end
  end,
}
```

**Comment by step4** [comment]
Thanks for the example and quick help!

I had to remove `<C-u>` and `<C-d>` from the default `mappings` property as well:
```lua
plugins = {
    neoscroll = {
      mappings = { "<C-b>", "<C-f>", "<C-y>", "<C-e>", "zt", "zz", "zb" },
    },
  },
```

I think the config here: https://github.com/kabinspace/AstroVim/blob/3ac533a01872b4d48e08dffc90ec404d64d46acc/lua/configs/neoscroll.lua#L11 will always set the default mappings if the `mappings` property is not overridden.

The part in my polish function is then:
```lua
local neoscroll_avail, neoscroll_config = pcall(require, "neoscroll.config")
   if neoscroll_avail then
   neoscroll_config.set_mappings {
        ["<C-u>"] = { "scroll", { "-vim.wo.scroll", "true", "50" } },
        ["<C-d>"] = { "scroll", { "vim.wo.scroll", "true", "50" } },
    }
end
```
