### ISSUE TITLE
optonal job numers to toggle terminals

### ISSUE THREAD

**Issue by kraxli** [kabinspace/AstroVim#296]
a feature enhancement request:

allow for optional **job numbers** for toggling terms (see: https://github.com/akinsho/toggleterm.nvim#custom-terminals)

**Comment by mehalter** [comment]
What do the job numbers provide that the current implementation is missing?

**Comment by mehalter** [comment]
The linked PR extends the abilities of the toggleterminal helper function so when you create a key binding you can either just provide the `cmd` as a string or a full table with all of the available options when calling `Terminal:new()`.
