### ISSUE TITLE
better lazygit support

### ISSUE THREAD

**Issue by kraxli** [kabinspace/AstroVim#297]
from my experience with [lunarvim](https://github.com/LunarVim/LunarVim/blob/rolling/lua/lvim/core/terminal.lua), lazygit git can look much better in toggleterm terminal (see also https://github.com/akinsho/toggleterm.nvim#custom-terminals). 
Would it be possible to improve lazygit in your base config of AstroVim?
Many thanks!

**Comment by mehalter** [comment]
Do you mean just adding the border around the lazygit terminal? Just want to make sure because I can't find anything else different between the link you sent and the current implementation

**Comment by kraxli** [comment]
sorry my bad. It is kind of the coloring. After choosing `colorscheme elford`  on both config for comparability, they look pretty much the same.

**Comment by kraxli** [comment]
it seems that the colors for lazygit / terminal are fixed and they do not work for all colorschemes (e.g. the once with a `set background = light`
