### ISSUE TITLE
remap default which-key binding

### ISSUE THREAD

**Issue by kraxli** [kabinspace/AstroVim#298]
sorry for the "spam" ...
I would like to remap
` ["tp"] = { "<cmd>lua require('core.utils').toggle_term_cmd('ipython')<CR>", "Python" },` (ipython instead of python) in my `register_n_leader.lua` file which in general works fine. However, the remap of `["tp"] ` doesn't work.
How can I do this?

**Comment by mehalter** [comment]
you are quite close, which-key is done through menus, so I think the code you are looking for is this in your `init.lua` file:

```lua
return {
  ["which-key"] = {
    register_n_leader = {
      t = {
        p = { "<cmd>lua require('core.utils').toggle_term_cmd('ipython')<CR>", "Python" },
      },
    },
  },
}
```
