### ISSUE TITLE
send a line of file to a specifc terminal

### ISSUE THREAD

**Issue by kraxli** [kabinspace/AstroVim#299]
How can I send a line with `ToggleTermSendCurrentLine` to a specific terminal, e.g. python-terminal window? the line send by `ToggleTermSendCurrentLine` goes to the default terminal mapped to `<leader>tf` but not e.g. a file specific or latest terminal.

**Comment by mehalter** [comment]
This is a good point I haven't thought about yet. I think what we should do is extend the utils to provide access to the `user_terminals` variable. Then you could access the terminal id with `require("core.utils").user_terminals`. So getting the terminal id for your `ipython` terminal for example would be `require("core.utils").user_terminals.ipython.id` and you could provide that to the `ToggleTermSendCurrentLine` call.

**Comment by mehalter** [comment]
This extra extensability has been added in the linked PR.
