### ISSUE TITLE
Crtl-w force write conflict with the default switch windows key mapping

### ISSUE THREAD

**Issue by socialsmoker223** [kabinspace/AstroVim#3]
Use space-w or other key without conflict should be better

**Comment by kabinspace** [comment]
You can define your custom key bindings in lua/user/settings.lua file

**Comment by kabinspace** [comment]
For ease of navigation, the default key binding let's you switch to windows with ctrl key
For example: `Ctrl` + `l` let's you switch to the right window without needing you to press w key
