### ISSUE TITLE
Packer prompting to uninstall dashboard, presence and lsp_signature

### ISSUE THREAD

**Issue by pupperemeritus** [kabinspace/AstroVim#30]
When packer is synced, it prompted to uninstall dashboard,presence and lsp signature.  nothing seems to be off with the config files. I assumed that it would reinstall or something but now presence,dashboard and lsp_signature are gone.

**Comment by pupperemeritus** [comment]
packer_compiled.lua is untouched
my user/settings.lua
```
local opts = { noremap = true, silent = true }
local map = vim.api.nvim_set_keymap
local set = vim.opt

local config = {

  -- Set colorscheme
  colorscheme = "deep-space",

  -- Add plugins
  plugins = {
     { "andweeb/presence.nvim" },
     {
       "ray-x/lsp_signature.nvim",
       event = "BufRead",
       config = function()
         require("lsp_signature").setup()
       end,
     },
  },

  -- On/off virtual diagnostics text
  virtual_text = true,

  -- Disable default plugins
  enabled = {
    nvim_tree = true,
    lualine = true,
    lspsaga = true,
    gitsigns = true,
    colorizer = true,
    toggle_term = true,
    comment = true,
    symbols_outline = true,
    indent_blankline = true,
    dashboard = true,
    which_key = true,
    neoscroll = true,
    ts_rainbow = true,
    ts_autotag = true,
  },
}

-- Set options
set.relativenumber = true
set.termguicolors = true
set.background = dark
set.term = xterm-256color

-- Set key bindings
map("n", "<C-s>", ":w!<CR>", opts)

-- Set autocommands
vim.cmd [[
  augroup packer_conf
    autocmd!
    autocmd bufwritepost plugins.lua source <afile> | PackerSync
  augroup end
]]

return config
```

**Comment by kabinspace** [comment]
Everything looks about right in your `user/settings.lua`. That's a very odd thing to happen, can you try doing a reinstallation?

**Comment by pupperemeritus** [comment]
seems to be remedied by editing plugin.lua to include presence, and also removing the not in the disable = line.

**Comment by pupperemeritus** [comment]
dope config btw. left me jaw dropped. it introduced me  to lua based nvim configs. literally the config of my dreams it is. very few tweaks I would have to do to make nvim to my liking.

**Comment by kabinspace** [comment]
> seems to be remedied by editing plugin.lua to include presence, and also removing the not in the disable = line. if it acts up again i shall reinstall.

Really strange that you had to make direct changes in `plugins.lua`, should have worked from the `settings.lua` alone. I still couldn't find a single clue on what might be the cause of it. I'll let you know if i find anything helpful

**Comment by kabinspace** [comment]
> dope config btw. left me jaw dropped. it introduced me to lua based nvim configs. literally the config of my dreams it is. very few tweaks I would have to do to make nvim to my liking.

Yes, lua is good indeed, glad to know that you are enjoying it :)

**Comment by pupperemeritus** [comment]
I reinstalled, the first time it prompted but after some update to packer. There were some deprecated lines I cant remember in which, iirc load.lua of one of the plugins at the package site, "loadstring" was the deprecated function which was replaced with "load", replacing instances of which reduced the errors that I had.

**Comment by pupperemeritus** [comment]
looks like something wrong with clean.lua in .local/site/..../packer/....

**Comment by pupperemeritus** [comment]
The issue is back again, and i cant seem to update AstroVim now. Says update failed:table 0x7fa2f3f3c468

**Comment by pupperemeritus** [comment]
Looks like for some reason it isnt respecting settings.lua

**Comment by pupperemeritus** [comment]
I think i found the issue for real this time. Its so tiny lol. 
```
    { "farmergreg/vim-lastplace",
      "junegunn/limelight.vim",
      "junegunn/goyo.vim",
      "tyrannicaltoucan/vim-deep-space",
      "danilo-augusto/vim-afterglow",
    },
  },
```
The issue here was the first line where I had just sent that first line of text to the next line while keeping the bracket there.
The first line here in my config apparently affected the entire file by not returning user config so it reverted to defaults.
All good now.
