### ISSUE TITLE
Change theme

### ISSUE THREAD

**Issue by jeremyscatigna** [kabinspace/AstroVim#36]
Is there a way to change the theme or the possibility to add new ones ?

**Comment by hugang** [comment]
this works for me.
![2022-02-11_172914](https://user-images.githubusercontent.com/1448114/153559743-530db0e2-e145-407f-b189-595c341ed3ce.png)

**Comment by kabinspace** [comment]
@jeremyscatigna You are supposed to install the theme that you want to use and set the name of the theme [here](https://github.com/kabinspace/AstroVim/blob/7181ca684e4e5e7a3d1044466d0665831904a429/lua/user/settings.lua#L8) as @hugang has shown in the ss.

**Comment by jeremyscatigna** [comment]
It does not work for me with this theme: https://github.com/catppuccin/nvim

**Comment by kabinspace** [comment]
@jeremyscatigna I just tried this and it works, did you follow the steps carefully? Make sure you have done something similar to this
![itworkss](https://user-images.githubusercontent.com/91150148/153618876-78bdb5fc-05cb-428a-bfc3-88dfc6bab1b5.png)
