### ISSUE TITLE
I'd really appretiate help to redefine bindings

### ISSUE THREAD

**Issue by gabriel-viviani** [kabinspace/AstroVim#37]
I've read [mapping](https://github.com/kabinspace/AstroVim/blob/main/utils/mappings.txt) and also [user guide](https://github.com/kabinspace/AstroVim/blob/main/utils/userguide.md) to find out basic usage of Awesome AstroVim.

Although As a totally newbie in lua and not a fully connoisseur of neovim bindings, I have no idea on how to change default AstroVim bindings to mine.

A fast tutorial on how to do that would be great.

Thanks for awesome work!

**Comment by pupperemeritus** [comment]
Check ~/.config/nvim/lua/core/mappings.lua , You can change things from there and the syntax is pretty straightforward. Might also want to create a backup in a different folders so in case of an update you wont lose your mappings. I dont think updating changes them though but just to be safe.

**Comment by kabinspace** [comment]
@gabriel-viviani Is your problem solved?
