### ISSUE TITLE
Telescope issue on fresh install

### ISSUE THREAD

**Issue by pierrenel** [kabinspace/AstroVim#4]
Installed nvim 0.6.1 via homebrew, then Astrovim as per the instructions, ran PackerSync and PackerCompile, but still seeing:

```
Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:83: Vim:E492: Not an editor command: Telescope find_files
Please check your config for correctness
Press ENTER or type command to continue
```

on space f f  or space f o

Also installed fd via homebrew - didn't help either 🤔

**Comment by Chaz6** [comment]
I had this issue (see #1) and it was because my neovim executable was called `neovim`. I made a link to `nvim` and it worked for me (you may need to start with a fresh installation of AstroVim).

**Comment by pierrenel** [comment]
Curious - are you on a mac?

```
❯ cd /usr/local/bin
❯ ls -lha | grep nvim
lrwxr-xr-x    1 pierre  admin     4B Feb  4 11:49 neovim -> nvim
lrwxr-xr-x    1 pierre  admin    31B Feb  4 11:23 nvim -> ../Cellar/neovim/0.6.1/bin/nvim
❯ which nvim
/usr/local/bin/nvim
```

**Comment by kabinspace** [comment]
Did your issue get solved from #1 ?

**Comment by kabinspace** [comment]
I just recently encountered that issue myself, Here's the fix https://github.com/kabinspace/AstroVim/commit/2c340e99f78fcd5c35afc3c217f3536e6709e5d8 for that.

**Comment by thefatstack** [comment]
@kabinspace I still have the error message for the find function.

`                    packer.nvim: Error running config for telescope.nvim: ...er/opt/telescope.nvim/lua/telescope/_extensions/init.lua:10: This extension doesn't exist or is not installed: fzf
...ck/packer/start/impatient.nvim/lua/impatient/profile.lua:148: module 'telescope._extensions.fzf' not found:
^Ino field package.preload['telescope._extensions.fzf']No cache entry
^Ino file './telescope/_extensions/fzf.lua'
^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220111/share/luajit-2.1.0-beta3/telescope/_extensions/fzf.lua'
^Ino file '/usr/local/share/lua/5.1/telescope/_extensions/fzf.lua'
^Ino file '/usr/local/share/lua/5.1/telescope/_extensions/fzf/init.lua'
^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220111/share/lua/5.1/telescope/_extensions/fzf.lua'
^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220111/share/lua/5.1/telescope/_extensions/fzf/init.lua'
^Ino file '/Users/tranphongbb/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/telescope/_extensions/fzf.lua'
^Ino file '/Users/tranphongbb/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/telescope/_extensions/fzf/init.lua'
^Ino file '/Users/tranphongbb/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/telescope/_extensions/fzf.lua'
^Ino file '/Users/tranphongbb/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/telescope/_extensions/fzf/init.lua'
^Ino file './telescope/_extensions/fzf.so'
^Ino file '/usr/local/lib/lua/5.1/telescope/_extensions/fzf.so'
^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220111/lib/lua/5.1/telescope/_extensions/fzf.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/Users/tranphongbb/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/telescope/_extensions/fzf.so'
^Ino file './telescope.so'
^Ino file '/usr/local/lib/lua/5.1/telescope.so'
^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220111/lib/lua/5.1/telescope.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'`

**Comment by kabinspace** [comment]
I just recently updated a fix for it, can you try reinstalling it again?

**Comment by thefatstack** [comment]
@kabinspace i tried to reinstalling it, but it still showing errors

**Comment by kabinspace** [comment]
@thefatstack does using the find function still trigger the error even though it is working?

**Comment by thefatstack** [comment]
@kabinspace yes it does

**Comment by kabinspace** [comment]
@thefatstack are you 100% sure that you have this https://github.com/kabinspace/AstroVim/commit/2c340e99f78fcd5c35afc3c217f3536e6709e5d8 update on your config?

**Comment by thefatstack** [comment]
@thefatstack I checked it and am pretty sure I have the update. I also try `:PackerSync` but the error still trigger

**Comment by kabinspace** [comment]
@thefatstack I tried reinstalling this several times to see if the error appears on mine but it didn't, in this case, the only solution for now is to delete the "nvim-telescope/telescope-fzf-native.nvim" plugin which is located in lua/core/plugins.lua from line number 239-244. Let me know if doing this worked.

**Comment by rozari0** [comment]
I Just Installed, but facing same issue.

**Comment by kabinspace** [comment]
@thefatstack this right here https://github.com/kabinspace/AstroVim/commit/c0a0baca6e2aadb13ed14e4179c9d296b931468f should fix your problem, can you try one last reinstallation? and let me know if this one worked

**Comment by pierrenel** [comment]
- did a reinstall, it's working beautifully <3

**Comment by thefatstack** [comment]
@kabinspace nicely done. thank you for your support

**Comment by iblezya** [comment]
@kabinspace Thanks for that quick fix.
