### ISSUE TITLE
I made a YouTube video ✨ 

### ISSUE THREAD

**Issue by jpmcb** [kabinspace/AstroVim#48]
Hi all - love the project so I went ahead and made [a YouTube video about Astro Vim](https://youtu.be/JQLZ7NJRTEo) and just wanted to share here!

Keep up the great work!

**Comment by kabinspace** [comment]
@jpmcb I just watched the video and it was really great. Thank you for the support :)

**Comment by kabinspace** [comment]
@jpmcb I will be adding this to the readme so that people can see what to expect from AstroVim :)

**Comment by jpmcb** [comment]
Ah that's great! Keep up the good work!! 🙏🏼
