### ISSUE TITLE
[FR] Integrate Vista for ctags usage

### ISSUE THREAD

**Issue by Daemoen** [kabinspace/AstroVim#5]
Love the config.  Love the integrated explorer, the ease to use, etc....  One thing I was surprised by was the lack of a ctags plugin.  Would be great to see something like Vista integrated.

**Comment by Daemoen** [comment]
Found SymbolsOutline, does more or less the same thing.  Just need to add some friendly binding for it.

**Comment by kabinkarki** [comment]
`Space` + `s` is the default key binding for symbols outline. You can define your custom set of key bindings in lua/user/settings.lua file.

**Comment by kabinspace** [comment]
@Daemon by default you can open symbols outline with `Space` + `s` but if you want something that's more comfortable for you then you can add your own key bindings in lua/user/settings.lua file. I would also recommend you to check out https://github.com/kabinspace/AstroVim/blob/main/utils/mappings.txt this mapping file to know more about the default key bindings.
