### ISSUE TITLE
AstroVim: This extension doesn't exist or is not installed: fzf

### ISSUE THREAD

**Issue by Panchitoz1** [kabinspace/AstroVim#58]
Hello there!

I'm currently using AstroVim on Ubuntu 20.04 running in WSL2. When I launch AstroVim everything is fine (i.e., it starts without problems). However, when I try to 'Find File' (Space + F +  F), for example, I get the error given in the title since some Telescope plugin files are apparently not recognizing 'fzf' extension. This does not break Neovim itself; I can keep using it. But there are some troubles trying to navigate through directories.

To be more specific, this is the exact error:
` packer.nvim: Error running config for telescope.nvim: ...er/opt/telescope.nvim/lua/telescope/_extensions/init.lua:10: This extension doesn't exist or is not installed: fzf`

This same issue/bug has been reported in LunarVim (which is like AstroVim's cousin): [[Bug] This extension doesn't exist or is not installed: fzf #1804](https://github.com/LunarVim/LunarVim/issues/1804)

Apparently, the best way to fix this problem is given by this [reply](https://github.com/LunarVim/LunarVim/issues/1804#issuecomment-963507212) (best rated one).

Quoting, it says:

> Again, this has nothing to do with having the fzf binary installed or not, it's about https://github.com/nvim-telescope/telescope-fzf-native.nvim
Try this please:
>`
:! make -C $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim`
>You can also do make clean just to be sure
>`:! cd $LUNARVIM_RUNTIME_DIR/site/pack/packer/start/telescope-fzf-native.nvim && make clean && make`

Is there a similar (or different) solution for this issue/bug for AstroVim? Since this issue has appeared a lot in LunarVim and is also present in AstroVim a 'patch' or a solution would be great to improve this Neovim config. 

Cheers!

**Comment by kabinspace** [comment]
Are you sure you are on the latest update of AstroVIm, I addressed this problem over [here](https://github.com/kabinspace/AstroVim/issues/4#issuecomment-1030220457). It did solve the problem for that period.

**Comment by Panchitoz1** [comment]
Yes, I do. I installed AstroVim in this machine last Friday (February 12th, 2021) cloning the repository and applying ther packer sync. Also, even if I try `:checkhealth telescope` it gives `ERROR:  No healthcheck found for "telescope" plugin`.

**Comment by milosavljevicoa** [comment]
I am experiencing the same issue. First time cloning this project, which is awesome btw, on ubuntu (wsl2 not sure that this information matters)

**Comment by milosavljevicoa** [comment]
I found a solution by using `nvim-telescope/telescope-fzy-native.nvim` instead of `nvim-telescope/telescope-fzy-native.nvim` inside `plugins.lua` and then updating line in `telescope.lua` to `telescope.load_extension "fzy_native"` from `telescope.load_extension "fzf"`. Not really sure what are the differences between `fzy` and `fzf`. Hope this helps 😄

**Comment by moojing** [comment]
I solve the issue by going into the folder of the plugin`telescope-fzf-native.nvim`, 
and then execute the command `make`. 

maybe it's because some how the plugin doesn't produce the built file by default?

**Comment by odyslam** [comment]
@moojing for my life, I can't find the plugin's folder. 

Can you share your path?

**Comment by hp4k1h5** [comment]
> I solve the issue by going into the folder of the plugin`telescope-fzf-native.nvim`, and then execute the command `make`.
> 
> maybe it's because some how the plugin doesn't produce the built file by default?

if `make` by itself does not work try `make clean` first and then `make` from `~/.local/share/nvim/lazy/telescope-fzf-native.nvim` as suggested by [this comment](https://github.com/LunarVim/LunarVim/issues/1804#issue-1029963964)

**Comment by eerison** [comment]
> > I solve the issue by going into the folder of the plugin`telescope-fzf-native.nvim`, and then execute the command `make`.
> > maybe it's because some how the plugin doesn't produce the built file by default?
> 
> if `make` by itself does not work try `make clean` first and then `make` from `~/.local/share/nvim/lazy/telescope-fzf-native.nvim` as suggested by [this comment](https://github.com/LunarVim/LunarVim/issues/1804#issue-1029963964)

thank you, it worked  <3

**Comment by AndSonder** [comment]
For my m3 macbook, go to `~/.local/share/nvim/lazy/telescope-fzf-native.nvim` and run `make clean && arch -arm64 make` works well for me.
