### ISSUE TITLE
lua/user/settings.lua plugins not loading

### ISSUE THREAD

**Issue by aikakira** [kabinspace/AstroVim#6]
Hello!

Thanks for this awesome setup, it's amazing how pretty you've made everything! I'm struggling with adding new plugins via the user/settings.lua file. I can't seem to make packer sync my additional plugins, if I add them to lua/core/defaults.lua everything works and installs.

P.S Fresh install here

**Comment by kabinspace** [comment]
@aikakira can you show me the settings.lua where you put your plugins once? i tried to look if something was wrong but I couldn't find any, maybe i can get some clues from you.

**Comment by nielsk** [comment]
I have the same problem. Mine looks like this, I just added fugitive (because I do not yet under Gitsigns and apparently it integrates with fugitive) and the color-theme Ayu:

```
local opts = { noremap = true, silent = true }
local map = vim.api.nvim_set_keymap
local set = vim.opt

local config = {

  -- Set colorscheme
  colorscheme = "onedark",

  -- Add plugins
  plugins = {
    -- { "andweeb/presence.nvim" },
    -- { "tpope/vim-fugitive" },
    -- { "ayu-theme/ayu-vim" },
    -- {
      -- "ray-x/lsp_signature.nvim",
      -- event = "BufRead",
      -- config = function()
        -- require("lsp_signature").setup()
      -- end,
    -- },
  },

  -- On/off virtual diagnostics text
  virtual_text = true,

  -- Disable default plugins
  enabled = {
    nvim_tree = true,
    lualine = true,
    lspsaga = true,
    gitsigns = true,
    colorizer = true,
    toggle_term = true,
    comment = true,
    symbols_outline = true,
    indent_blankline = true,
    dashboard = true,
    which_key = true,
    neoscroll = true,
    ts_rainbow = true,
    ts_autotag = true,
  },
}

-- Set options
set.relativenumber = true

-- Set key bindings
map("n", "<C-s>", ":w!<CR>", opts)

-- Set autocommands
vim.cmd [[
  augroup packer_conf
    autocmd!
    autocmd bufwritepost plugins.lua source <afile> | PackerSync
  augroup end
]]

return config
```

**Comment by nielsk** [comment]
And maybe it is just a layer8-problem - after I added the plugins, what would I need to do?

**Comment by nielsk** [comment]
I also just set neoscroll to false and it seems not to change anything

**Comment by nielsk** [comment]
I deleted the -- in the plugins-part and that worked for me. Oh the "--" are comments 🤦 
Not knowing lua that was a show-stopper for me.

**Comment by aikakira** [comment]
> @aikakira can you show me the settings.lua where you put your plugins once? i tried to look if something was wrong but I couldn't find any, maybe i can get some clues from you.

This is my settings.lua

`local opts = { noremap = true, silent = true }
local map = vim.api.nvim_set_keymap
local set = vim.opt

local config = {

  -- set colorscheme
  colorscheme = "onedark",

  -- add plugins
  plugins = {
    { "tpope/vim-surround" },
    { "tpope/vim-fugitive" }
  },

  -- on/off virtual diagnostics text
  virtual_text = true,

  -- disable default plugins
  enabled = {
    nvim_tree = true,
    lualine = true,
    lspsaga = true,
    gitsigns = true,
    colorizer = true,
    toggle_term = true,
    comment = true,
    symbols_outline = true,
    indent_blankline = true,
    dashboard = true,
    which_key = true,
    neoscroll = true,
    ts_rainbow = true,
    ts_autotag = true,
  },
}

-- set options
set.relativenumber = true

-- set key bindings
map("n", "<c-s>", ":w!<cr>", opts)

-- set autocommands
vim.cmd [[
  augroup packer_conf
    autocmd!
    autocmd bufwritepost plugins.lua source <afile> | packersync
  augroup end
]]

return config`

Thank you!

**Comment by nielsk** [comment]
@aikakira aren't you missing a ","? 
```
{ "tpope/vim-fugitive" }
```
should be
```
{ "tpope/vim-fugitive" },
```
I think

**Comment by kabinspace** [comment]
@aikakira I just copy-pasted your settings.lua and it seems to work for me, can you try `:PackerInstall` once and see if it downloads? Also check if it is installed or not with `PackerStatus`

**Comment by kabinspace** [comment]
@nielsk removing the comment worked for you? Any other problems you got?

**Comment by nielsk** [comment]
So far everything works :)
Thanks for asking

**Comment by aikakira** [comment]
> @aikakira I just copy-pasted your settings.lua and it seems to work for me, can you try `:PackerInstall` once and see if it downloads? Also check if it is installed or not with `:PackerStatus`

@kabinspace Thanks again for looking into this for me, so I've removed the lines in default.lua and changed to use user/settings.lua. :PackerInstall doesn't actually do anything from what I can tell, I've found the if I quid neovim then start it again, I can use :PackerSync and it'll install.

P.S After changing the file I also do :source / :so just incase before running :PackerSync - also I'm on Fedora if that has any relation

**Comment by kabinspace** [comment]
@aikakira I still can't seem to find out anything that might cause this problem yet. There wasn't really anything wrong with your settings.lua either, have you tried reinstalling it once?

**Comment by aikakira** [comment]
> @aikakira I still can't seem to find out anything that might cause this problem yet. There wasn't really anything wrong with your settings.lua either, have you tried reinstalling it once?

Thanks again for trying! I'll reinstall and see what happens :+1: , the original issue doesn't happen anymore and I can update with my user settings file therefore I'm going to close the issue, thanks again for the swift replies and great work!
