### ISSUE TITLE
Can't get it to work on Windows

### ISSUE THREAD

**Issue by Paarth-1504** [kabinspace/AstroVim#66]
I have AstroVim on my arch install and love using it, was wondering if I could use on my windows machine as well.
If so, could you please walk me through it ?

 Thanks!!

**Comment by kabinspace** [comment]
Sorry, AstroVim was aimed specifically for Linux only, I can't provide you any support in this case but there are few people in AstroVim [discord](https://discord.gg/UcZutyeaFW) server who are able to run it on Windows.
