### ISSUE TITLE
WhichKey is not in sync with documentation

### ISSUE THREAD

**Issue by xoac** [kabinspace/AstroVim#68]
The output of `:WhichKey` 
![image](https://user-images.githubusercontent.com/1863020/153955946-90e1b6bc-1e6f-4b20-bbc0-52dd795edf51.png)

The mapping: https://github.com/kabinspace/AstroVim/blob/a4454f33c3d43bdcb81ceb1d08dcc1e6109b1f62/utils/mappings.txt
For example there is no **`dg` - go to definition**. but you will find more. I think everything from lsp is not present here.

**Comment by kabinspace** [comment]
@xoac There is a lsp menu for whick-key, hit the `space` and you will see `l` for lsp options. I haven't included everything to not clutter the menu with key bindings. And for go to definition, AsroVIm doesn't use `dg` like you mentioned, it uses `gd` instead.
