### ISSUE TITLE
Is there an option for transparency?

### ISSUE THREAD

**Issue by darklight-oss** [kabinspace/AstroVim#8]
NvChad had an option to turn on transparency.
Does AstroVim has that option as well?

**Comment by kabinspace** [comment]
Currently, AstroVim doesn't have an option for turning on/off transparency,

**Comment by kabinspace** [comment]
@darklight-oss You can make some changes in colorscheme if you want transparency, at the end of lua/onedark/init.lua file, you can add some of your own custom highlighting group like this:
```lua
vim.cmd("hi Normal guibg=NONE ctermbg=NONE")
vim.cmd("hi CursorColumn cterm=NONE ctermbg=NONE ctermfg=NONE")
vim.cmd("hi CursorLine cterm=NONE ctermbg=NONE ctermfg=NONE")
vim.cmd("hi CursorLineNr cterm=NONE ctermbg=NONE ctermbg=NONE")
vim.cmd("hi clear LineNr")
vim.cmd("hi clear SignColumn")
vim.cmd("hi clear StatusLine")
```

**Comment by kabinspace** [comment]
I'm not really sure if this is the type of transparency you want but you could make some of your own adjustment.

**Comment by darklight-oss** [comment]
> @darklight-oss You can make some changes in colorscheme if you want transparency, at the end of lua/onedark/init.lua file, you can add some of your own custom highlighting group like this:
> 
> ```lua
> vim.cmd("hi Normal guibg=NONE ctermbg=NONE")
> vim.cmd("hi CursorColumn cterm=NONE ctermbg=NONE ctermfg=NONE")
> vim.cmd("hi CursorLine cterm=NONE ctermbg=NONE ctermfg=NONE")
> vim.cmd("hi CursorLineNr cterm=NONE ctermbg=NONE ctermbg=NONE")
> vim.cmd("hi clear LineNr")
> vim.cmd("hi clear SignColumn")
> vim.cmd("hi clear StatusLine")
> ```

That pretty much did it :)

**Comment by mehalter** [comment]
For anyone coming back to this issue as reference, there have been some significant user improvements to the `default_theme` and user configuration. This same effect can be easily configured in the `user/init.lua` file entirely in lua now without calling `vim.cmd [[...]]`:

```lua
return {
  default_theme = {
    highlights = function(hi)
      local C = require "default_theme.colors"
      hi.Normal = {bg = C.none, ctermbg = C.none}
      hi.CursorColumn = {cterm = {}, ctermbg = C.none, ctermfg = C.none}
      hi.CursorLine = {cterm = {}, ctermbg = C.none, ctermfg = C.none}
      hi.CursorLineNr = {cterm = {}, ctermbg = C.none, ctermfg = C.none}
      hi.LineNr = {}
      hi.SignColumn = {}
      hi.StatusLine = {}
      return hi
    end,
  },
}
```

**Comment by Korokoukousei** [comment]
But i'm not using a default theme, how do I intergrate this in my init.lua?

```
-- Set colorscheme
local colorscheme = "default_theme"

local theme_installed, _ = pcall(require, "gruvbox")
if theme_installed then
  colorscheme = "gruvbox"
end

local config = {
  colorscheme = colorscheme,

  -- Default theme configuration
  default_theme = {
    diagnostics_style = { italic = true },
    -- Modify the color table
    colors = {
      fg = "#abb2bf",
    },
    -- Modify the highlight groups
    highlights = function(highlights)
      local C = require "default_theme.colors"

      highlights.Normal = { fg = C.fg, bg = C.bg }
      return highlights
    end,
  },

  -- Disable default plugins
  enabled = {
    bufferline = true,
    neo_tree = true,
    lualine = true,
    gitsigns = true,
    colorizer = true,
    toggle_term = true,
    comment = true,
    symbols_outline = true,
    indent_blankline = true,
    dashboard = true,
    which_key = true,
    neoscroll = true,
    ts_rainbow = true,
    ts_autotag = true,
  },

  -- Disable AstroNvim ui features
  ui = {
    nui_input = true,
    telescope_select = true,
  },

  -- Configure plugins
  plugins = {
    -- Add plugins, the packer syntax without the "use"
    init = function(plugins)
      local my_plugins = {
        { "andweeb/presence.nvim" },
        { "ThePrimeagen/vim-be-good" },
        {
            "folke/todo-comments.nvim",
            requires = "nvim-lua/plenary.nvim",
            config = function()
                require("todo-comments").setup()
            end
        },
        { "superevilmegaco/Screenshot.nvim" },
        {
          "ellisonleao/gruvbox.nvim",
          as = "gruvbox",
        },

        -- {
        --   "ray-x/lsp_signature.nvim",
        --   event = "BufRead",
        --   config = function()
        --     require("lsp_signature").setup()
        --   end,
        -- },
      }

      plugins["Darazaki/indent-o-matic"] = nil

      return vim.tbl_deep_extend("force", plugins, my_plugins)
    end,
    -- All other entries override the setup() call for default plugins
    treesitter = {
      ensure_installed = { "lua", "c", "cpp", "javascript", "python" },
    },
    packer = {
      compile_path = vim.fn.stdpath "config" .. "/lua/packer_compiled.lua",
    },
  },

  -- Add paths for including more VS Code style snippets in luasnip
  luasnip = {
    vscode_snippet_paths = {},
  },

  -- Modify which-key registration
  ["which-key"] = {
    -- Add bindings to the normal mode <leader> mappings
    register_n_leader = {
      -- ["N"] = { "<cmd>tabnew<cr>", "New Buffer" },
    },
  },

  -- CMP Source Priorities
  -- modify here the priorities of default cmp sources
  -- higher value == higher priority
  -- The value can also be set to a boolean for disabling default sources:
  -- false == disabled
  -- true == 1000
  cmp = {
    source_priority = {
      nvim_lsp = 1000,
      luasnip = 750,
      buffer = 500,
      path = 250,
    },
  },

  -- Extend LSP configuration
  lsp = {
    -- add to the server on_attach function
    -- on_attach = function(client, bufnr)
    -- end,

    -- override the lsp installer server-registration function
    -- server_registration = function(server, opts)
    --   server:setup(opts)
    -- end

    -- Add overrides for LSP server settings, the keys are the name of the server
    ["server-settings"] = {
      -- example for addings schemas to yamlls
      -- yamlls = {
      --   settings = {
      --     yaml = {
      --       schemas = {
      --         ["http://json.schemastore.org/github-workflow"] = ".github/workflows/*.{yml,yaml}",
      --         ["http://json.schemastore.org/github-action"] = ".github/action.{yml,yaml}",
      --         ["http://json.schemastore.org/ansible-stable-2.9"] = "roles/tasks/*.{yml,yaml}",
      --       },
      --     },
      --   },
      -- },
    },
  },

  -- Diagnostics configuration (for vim.diagnostics.config({}))
  diagnostics = {
    virtual_text = true,
    underline = true,
  },

  -- null-ls configuration
  ["null-ls"] = function()
    -- Formatting and linting
    -- https://github.com/jose-elias-alvarez/null-ls.nvim
    local status_ok, null_ls = pcall(require, "null-ls")
    if not status_ok then
      return
    end

    -- Check supported formatters
    -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
    local formatting = null_ls.builtins.formatting

    -- Check supported linters
    -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
    local diagnostics = null_ls.builtins.diagnostics

    null_ls.setup {
      debug = false,
      sources = {
        -- Set a formatter
        formatting.rufo,
        -- Set a linter
        diagnostics.rubocop,
      },
      -- NOTE: You can remove this on attach function to disable format on save
      on_attach = function(client)
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = vim.lsp.buf.formatting_sync,
          })
        end
      end,
    }
  end,

  -- This function is run last
  -- good place to configure mappings and vim options
  polish = function()
    local map = vim.keymap.set
    local set = vim.opt
    -- Set options
    set.relativenumber = true
    set.shiftwidth = 4 -- Number of space inserted for indentation
    set.tabstop = 4 -- Number of space in a tab

    -- Set key bindings
    map("n", "<C-s>", ":w!<CR>")
    map("n", "C-c", "\"+y")
    map("n", "C-v", "\"+p")

    -- Set autocommands
    vim.api.nvim_create_augroup("packer_conf", {})
    vim.api.nvim_create_autocmd("BufWritePost", {
      desc = "Sync packer after modifying plugins.lua",
      group = "packer_conf",
      pattern = "plugins.lua",
      command = "source <afile> | PackerSync",
    })
    vim.g.dashboard_custom_header = {
        " ",
        " ",
        " ",
            " ",
        "▓█████▄  ▄▄▄        ██████  ██░ ██  ▄▄▄▄    ▒█████   ▄▄▄       ██▀███  ▓█████▄ ",
        "▒██▀ ██▌▒████▄    ▒██    ▒ ▓██░ ██▒▓█████▄ ▒██▒  ██▒▒████▄    ▓██ ▒ ██▒▒██▀ ██▌",
        "░██   █▌▒██  ▀█▄  ░ ▓██▄   ▒██▀▀██░▒██▒ ▄██▒██░  ██▒▒██  ▀█▄  ▓██ ░▄█ ▒░██   █▌",
        "░▓█▄   ▌░██▄▄▄▄██   ▒   ██▒░▓█ ░██ ▒██░█▀  ▒██   ██░░██▄▄▄▄██ ▒██▀▀█▄  ░▓█▄   ▌",
        "░▒████▓  ▓█   ▓██▒▒██████▒▒░▓█▒░██▓░▓█  ▀█▓░ ████▓▒░ ▓█   ▓██▒░██▓ ▒██▒░▒████▓ ",
        " ▒▒▓  ▒  ▒▒   ▓▒█░▒ ▒▓▒ ▒ ░ ▒ ░░▒░▒░▒▓███▀▒░ ▒░▒░▒░  ▒▒   ▓▒█░░ ▒▓ ░▒▓░ ▒▒▓  ▒ ",
        " ░ ▒  ▒   ▒   ▒▒ ░░ ░▒  ░ ░ ▒ ░▒░ ░▒░▒   ░   ░ ▒ ▒░   ▒   ▒▒ ░  ░▒ ░ ▒░ ░ ▒  ▒ ",
        " ░ ░  ░   ░   ▒   ░  ░  ░   ░  ░░ ░ ░    ░ ░ ░ ░ ▒    ░   ▒     ░░   ░  ░ ░  ░ ",
        "   ░          ░  ░      ░   ░  ░  ░ ░          ░ ░        ░  ░   ░        ░    ",
        " ░                                       ░                              ░      ",
        " ",
        " ",
        " ",
        " ",
        " ",
  }

    -- Set up custom filetypes
    -- vim.filetype.add {
    --   extension = {
    --     foo = "fooscript",
    --   },
    --   filename = {
    --     ["Foofile"] = "fooscript",
    --   },
    --   pattern = {
    --     ["~/%.config/foo/.*"] = "fooscript",
    --   },
    -- }
  end,
}

return config
```

**Comment by mehalter** [comment]
@Korokoukousei

**Comment by Korokoukousei** [comment]
@mehalter https://github.com/ellisonleao/gruvbox.nvim/issues/107
```
vim.t.is_transparent = 0
function toggle_transparent()
    if vim.t.is_transparent == 0 then
        vim.api.nvim_set_hl(0, "Normal", {guibg = NONE; ctermbg = NONE})
        vim.t.is_transparent = 1
    else
        vim.opt.background = "dark"
        vim.t.is_transparent = 0
    end
end
vim.keymap.set("n", "<F2>", toggle_transparent, opts)
```
where do i put this code in my init.lua?

**Comment by mehalter** [comment]
You can put that in your `polish` function

**Comment by ttnsgn** [comment]
> For anyone coming back to this issue as reference, there have been some significant user improvements to the `default_theme` and user configuration. This same effect can be easily configured in the `user/init.lua` file entirely in lua now without calling `vim.cmd [[...]]`:
> 
> ```lua
> return {
>   default_theme = {
>     highlights = function(hi)
>       local C = require "default_theme.colors"
>       hi.Normal = {bg = C.none, ctermbg = C.none}
>       hi.CursorColumn = {cterm = {}, ctermbg = C.none, ctermfg = C.none}
>       hi.CursorLine = {cterm = {}, ctermbg = C.none, ctermfg = C.none}
>       hi.CursorLineNr = {cterm = {}, ctermbg = C.none, ctermfg = C.none}
>       hi.LineNr = {}
>       hi.SignColumn = {}
>       hi.StatusLine = {}
>       return hi
>     end,
>   },
> }
> ```

Thank you, It works for me, but the neo tree on the left side doesn't affect by this config

**Comment by mehalter** [comment]
@ttnsgn We set a different background color for NeoTree to make it look nicer as a sidebar in our default theme. You can extend this to also make NeoTree transparent by also adding the same overrides for NeoTreeNormal and NeoTreeNormalNC

```lua
return {
  default_theme = {
    highlights = function(hi)
      local C = require "default_theme.colors"
      hi.Normal = {bg = C.none, ctermbg = C.none}
      hi.CursorColumn = {cterm = {}, ctermbg = C.none, ctermfg = C.none}
      hi.CursorLine = {cterm = {}, ctermbg = C.none, ctermfg = C.none}
      hi.CursorLineNr = {cterm = {}, ctermbg = C.none, ctermfg = C.none}
      hi.LineNr = {}
      hi.SignColumn = {}
      hi.StatusLine = {}
      hi.NeoTreeNormal = {bg = C.none, ctermbg = C.none}
      hi.NeoTreeNormalNC = {bg = C.none, ctermbg = C.none}
      return hi
    end,
  },
}
```

**Comment by ttnsgn** [comment]
> @ttnsgn We set a different background color for NeoTree to make it look nicer as a sidebar in our default theme. You can extend this to also make NeoTree transparent by also adding the same overrides for NeoTreeNormal and NeoTreeNormalNC
> 
> ```lua
> return {
>   default_theme = {
>     highlights = function(hi)
>       local C = require "default_theme.colors"
>       hi.Normal = {bg = C.none, ctermbg = C.none}
>       hi.CursorColumn = {cterm = {}, ctermbg = C.none, ctermfg = C.none}
>       hi.CursorLine = {cterm = {}, ctermbg = C.none, ctermfg = C.none}
>       hi.CursorLineNr = {cterm = {}, ctermbg = C.none, ctermfg = C.none}
>       hi.LineNr = {}
>       hi.SignColumn = {}
>       hi.StatusLine = {}
>       hi.NeoTreeNormal = {bg = C.none, ctermbg = C.none}
>       hi.NeoTreeNormalNC = {bg = C.none, ctermbg = C.none}
>       return hi
>     end,
>   },
> }
> ```

Yes, agree with you, it look nicer when a sidebar has it self color schema, but some how for current now I chose to make it transparent, thank you for your help

**Comment by azinsharaf** [comment]
> You can put that in your `polish` function
@mehalter 

the `polish` function works and make the page transparent with F2. very nice! But how can i have the transparency as the default setting.
I am using the configuration below but doesn't make any difference.

```
  options = {
    t = {
      is_transparent = 1,
    }
},
```

**Comment by mehalter** [comment]
The code for toggling the transparency is a function and that function is not being called. Just setting that variable to One doesn't actually change the background to transparent. Instead of setting the variable in your options file, it would probably be easier to just call the toggle function after you define it in your polish function @azinsharaf

**Comment by azinsharaf** [comment]
perfect! works this way. you are awesome! :)

**Comment by mehalter** [comment]
For anyone that runs into this, there have been some pretty nice improvements to AstroNvim that includes an API for setting highlight groups across any and/or all themes. With this we are actually able generalize the code for setting transparency to work with any theme :)

Here is an example `user/init.lua` file:

```lua
return {
  -- set highlight group for any theme
  -- the key is the name of the colorscheme or init
  -- the init key will apply to all colorschemes
  highlights = {
    -- apply highlight group to all colorschemes (include the default_theme)
    init = {
      -- set the transparency for all of these highlight groups
      Normal = { bg = "NONE", ctermbg = "NONE" },
      CursorColumn = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
      CursorLine = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
      CursorLineNr = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
      LineNr = {},
      SignColumn = {},
      StatusLine = {},
      NeoTreeNormal = { bg = "NONE", ctermbg = "NONE" },
      NeoTreeNormalNC = { bg = "NONE", ctermbg = "NONE" },
    },
  },
}
```

**Comment by mehalter** [comment]
@Mjb141 I have updated this comment above to resolve your question

**Comment by Mjb141** [comment]
Have updated and confirm that works, thanks!

**Comment by CaneMandarinesco** [comment]
i have an issue with transparency, everything is ok (all the terminal is transparent) except for empty lines, those are not transparent.

**Comment by dvoytik** [comment]
This is needed as well:
```lua
plugins = {
    -- ...
    ["notify"] = function(config)
      config.background_colour = "#000000";
      return config
    end,
}
```
Otherwise `nvim-notify` will complain.
I'd suggest to add your recipe to the documentation/FAQ.

**Comment by erodactyl** [comment]
The config works very well, but the tabs on top are still not transparent. Any idea how I can fix that?

**Comment by DancinParrot** [comment]
@mehalter For some reason, your code doesn't work for me, but I'm new to this, so it may very well just be due to my ignorance. I have merged @ghost code with your provided code, and it seems to work fine on my side.

Here's the code for those interested, it should be placed within the polish() function:
```lua
  polish = function()
    vim.t.is_transparent = 0
    function toggle_transparent()
        if vim.t.is_transparent == 0 then
            vim.api.nvim_set_hl(0, "Normal", {guibg = NONE; ctermbg = NONE})
            vim.api.nvim_set_hl(0, "NormalNC", {guibg = NONE; ctermbg = NONE})
            vim.api.nvim_set_hl(0, "CursorColumn", { cterm = {}; ctermbg = NONE; ctermfg = NONE})
            vim.api.nvim_set_hl(0, "CursorLine", { cterm = {}; ctermbg = NONE; ctermfg = NONE})
            vim.api.nvim_set_hl(0, "CursorLineNr", { cterm = {}; ctermbg = NONE; ctermfg = NONE})
            vim.api.nvim_set_hl(0, "LineNr", {})
            vim.api.nvim_set_hl(0, "SignColumn", {})
            vim.api.nvim_set_hl(0, "StatusLine", {})
            vim.api.nvim_set_hl(0, "NeoTreeNormal", {guibg = NONE; ctermbg = NONE})
            vim.api.nvim_set_hl(0, "NeoTreeNormalNC", {guibg = NONE; ctermbg = NONE})
            vim.t.is_transparent = 1
        else
            vim.opt.background = "dark"
            vim.t.is_transparent = 0
        end
    end
    toggle_transparent()
  end,
```

**Comment by DancinParrot** [comment]
> The config works very well, but the tabs on top are still not transparent. Any idea how I can fix that?

Got it to work, sort of. There's still the seperator in between.
![image](https://github.com/AstroNvim/AstroNvim/assets/63692048/17c94e37-92ff-4465-857c-679d7fc5d1e9)

I have to manually change the TabLine config in AstroNvim's heirline config file, as seen below:
Before:
![image](https://github.com/AstroNvim/AstroNvim/assets/63692048/231bd55d-8306-4baa-9f7a-9f74b951e8c9)
After:
![image](https://github.com/AstroNvim/AstroNvim/assets/63692048/796a1d69-9d0a-48e1-8fdc-a72083a732c5)

After which, I set the following lines to remove the tab line and win bar background.
```lua
function toggle_transparent()
           -- ...
            vim.api.nvim_set_hl(0, "WinBar", {})
            vim.api.nvim_set_hl(0, "TabLine", {})
           -- ...
end
```

Thoughts on this, and should I open an issue? @mehalter 
Seems like it's an inherent config issue within Astronvim's config, as no matter what I set, the tab line background won't change, unlike the status line and win bar.

**Comment by mehalter** [comment]
This is a good question for the discord @DancinParrot

**Comment by mehalter** [comment]
No need to open an issue since it's not a bug

**Comment by DancinParrot** [comment]
> No need to open an issue since it's not a bug

Sure! I'll move this to discord.

**Comment by DancinParrot** [comment]
Thanks to @RayJameson, I've got a working transparency config now, including the seperators. For anyone that's having the same issue with transparency, simply use the `transparent-nvim` plugin from astrocommunity, and add in the config (you may create a new file for this) as seen below:
```lua
return {
  {
    "transparent.nvim",
    opts = {
      extra_groups = { -- table/string: additional groups that should be cleared
        -- In particular, when you set it to 'all', that means all available groups
        "BqfPreviewFloat",
        "NormalFloat",
        "NormalNC",
        "NvimTreeNormal",
        "NeoTreeNormal",
        "NeoTreeNormalNC",
        "NeoTreePreview",
        "NeoTreeTabInactive",
        "LineNr",
        "CursorColumn",
        "CursorLine",
        "CursorLineNr",
        "FloatBorder",
        "WinBar",
        "WinBarNC",
        "TreesitterContext",
        "Pmenu",
        "DapUIPlayPause",
        "DapUIRestart",
        "DapUIStop",
        "DapUIStepOut",
        "DapUIStepBack",
        "DapUIStepInto",
        "DapUIStepOver",
        "DapUIPlayPauseNC",
        "DapUIRestartNC",
        "DapUIStopNC",
        "DapUIStepOutNC",
        "DapUIStepBackNC",
        "DapUIStepIntoNC",
        "DapUIStepOverNC",
        "SignColumn",
        "StatusLine",
        "TelescopeBorder",
        "TelescopeNormal",
        "TelescopePreviewNormal",
        "TelescopeResultsNormal",
        "TelescopePromptNormal",
        "TabLineFill",
        "TreesitterContextLineNumber",
        "QuickFixLine",
        "Pmenu",
        "PmenuSel",
        "PmenuSbar",
        "PmenuThumb",
        "NotifyINFOBody",
        "NotifyWARNBody",
        "NotifyERRORBody",
        "NotifyDEBUGBody",
        "NotifyTRACEBody",
        "NotifyINFOBorder",
        "NotifyWARNBorder",
        "NotifyERRORBorder",
        "NotifyDEBUGBorder",
        "NotifyTRACEBorder",
        "WhichKeyFloat",
      },
    },
  },
}
```

You may refer to Ray or my config for more info:
https://github.com/RayJameson/astronvim_config/blob/main/plugins/community.lua#L19-L81
https://github.com/DancinParrot/astronvim-dotfiles/blob/transparent/plugins/transparent-nvim.lua

**Comment by mehalter** [comment]
@DancinParrot you can also just add the `transparent-nvim` entry from AstroCommunity to have a single line in your user configuration :)

https://github.com/AstroNvim/astrocommunity/blob/dc7ea3b358eafd508261b8108a37dc3ca11b414e/lua/astrocommunity/utility/transparent-nvim/init.lua

Also if there are any highlight groups missing in that configuration, PRs are welcome and encouraged by the community to help improve the community led repository of plugins

**Comment by DancinParrot** [comment]
Nice! I was totally unaware of that. Though, I've just tried it out and it seems like the default config for transparent-nvim have left out a few plugins, specifically Telescope, but it's easily fixable.

**Comment by RayJameson** [comment]
> @DancinParrot you can also just add the `transparent-nvim` entry from AstroCommunity to have a single line in your user configuration :)
> 
> https://github.com/AstroNvim/astrocommunity/blob/dc7ea3b358eafd508261b8108a37dc3ca11b414e/lua/astrocommunity/utility/transparent-nvim/init.lua
> 
> Also if there are any highlight groups missing in that configuration, PRs are welcome and encouraged by the community to help improve the community led repository of plugins

I can submit a PR with those groups, however, it doesn't include all of the highlights of plugins in astrocommunity

**Comment by DancinParrot** [comment]
> > @DancinParrot you can also just add the `transparent-nvim` entry from AstroCommunity to have a single line in your user configuration :)
> > https://github.com/AstroNvim/astrocommunity/blob/dc7ea3b358eafd508261b8108a37dc3ca11b414e/lua/astrocommunity/utility/transparent-nvim/init.lua
> > Also if there are any highlight groups missing in that configuration, PRs are welcome and encouraged by the community to help improve the community led repository of plugins
> 
> I can submit a PR with those groups, however, it doesn't include all of the highlights of plugins in astrocommunity

You can submit mine, as I've added in a couple more classes that are not included within your configuration, specifically StatusLine, SignColumn, and whatnot. However, I'm not sure if this should be in the PR as I think it may be best to let the user choose whichever extra groups that they want to add in. Nevertheless, I think it may be included within the documentation at the very least.

**Comment by RayJameson** [comment]
> > > @DancinParrot you can also just add the `transparent-nvim` entry from AstroCommunity to have a single line in your user configuration :)
> > > https://github.com/AstroNvim/astrocommunity/blob/dc7ea3b358eafd508261b8108a37dc3ca11b414e/lua/astrocommunity/utility/transparent-nvim/init.lua
> > > Also if there are any highlight groups missing in that configuration, PRs are welcome and encouraged by the community to help improve the community led repository of plugins
> > 
> > 
> > I can submit a PR with those groups, however, it doesn't include all of the highlights of plugins in astrocommunity
> 
> You can submit mine, as I've added in a couple more classes that are not included within your configuration, specifically StatusLine, SignColumn, and whatnot. However, I'm not sure if this should be in the PR as I think it may be best to let the user choose whichever extra groups that they want to add in. Nevertheless, I think it may be included within the documentation at the very least.

I didn't include StatusLine for my own preference so it blends with my TMUX status line:
<img width="1728" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/67468725/a78854a7-79de-48f4-91d2-21c9c0d170d5">

I should actually remove some groups from my config, as they are duplicate for default groups, already set by the plugin (SignColumn is one of them), you can check default groups on the plugin github page

**Comment by Wadosh42** [comment]
For anyone finding this topic and getting stuck with "No specs found for module astrocommunity.utility.transparent-nvim", the plugin have been moved from "utility" to "color":

```diff
-  { import = "astrocommunity.utility.transparent-nvim" },
+  { import = "astrocommunity.color.transparent-nvim" },
```
