### ISSUE TITLE
Feature Request - add option for camelCase or snake_case motion movement

### ISSUE THREAD

**Issue by flamendless** [kabinspace/AstroVim#86]

**Comment by flamendless** [comment]
> @flamendless could you explain this a little bit more as to what you mean?

using motion keys like `w` should stop at the `_` (snake case) or next uppercase letter (camelCase)

**Comment by mehalter** [comment]
@flamendless you might want to check out this plugin for this behavior: https://github.com/bkad/CamelCaseMotion

I haven't used it personally but seems to be recommended online and supports camelCase and snake_case motions

**Comment by flamendless** [comment]
> @flamendless you might want to check out this plugin for this behavior: https://github.com/bkad/CamelCaseMotion
> 
> I haven't used it personally but seems to be recommended online and supports camelCase and snake_case motions

Thank you. will do.
