### ISSUE TITLE
Where is <leader>w mapped?

### ISSUE THREAD

**Issue by salehmu** [kabinspace/AstroVim#9]
I want to remap `<leader>ws` to split window, but it seems like `<leader>w` is already mapped to `cmd>w!<CR` however I can't find it anywhere in `lua/core/mappings.lua`

**Comment by kabinspace** [comment]
@salehumu it is located in lua/user/settings.lua file.

**Comment by salehmu** [comment]
@kabinspace I only can see `C-s` in `lua/user/settings.lua` [here](https://github.com/kabinspace/AstroVim/blob/main/lua/user/settings.lua#L48) I already have commented it but `<leader>w` still mapped to something

**Comment by kabinspace** [comment]
@salehmu my bad, it's actually linked with which key plugin, so to change that, you can go to `lua/configs/which-key.lua` file in line number `72`. You can delete that line and map your desired key bindings back to `lua/user/settings.lua` file
