### ISSUE TITLE
Coloring is not working properly

### ISSUE THREAD

**Issue by meanindra** [kabinspace/AstroVim#91]
![Screenshot from 2022-02-21 22-56-40](https://user-images.githubusercontent.com/36324543/155002727-d5292171-98a8-4101-bcc1-a502494f8cec.png)
In this picture _button_ and _Hello_ color is same and **"** color almost same like button.

**Comment by kabinspace** [comment]
@meanindra Sorry that's something i can't solve, this is most likely coming from the [treesiitter](https://github.com/nvim-treesitter/nvim-treesitter) plugin, you can open an issue about this on their repository.
