### ISSUE TITLE
How to uninstall the project

### ISSUE THREAD

**Issue by Eezi** [kabinspace/AstroVim#97]
Hi, I was wondering should the documentation also have the uninstall guidelines for users who just want to test this project?

**Comment by vnbubba** [comment]
> Hi, I was wondering should the documentation also have the uninstall guidelines for users who just want to test this project?

mv ~/.config/nvim ~/.config/astronvim

**Comment by Eezi** [comment]
Yea I first tried that but after the I moved it to the different path, it caused weird bug with packer plugin manager.
The bug got fixed after I removed  folder pack/packer from ~/.local/share/nvim/site.

Now old configurations works as it should.

**Comment by kaushalruparel** [comment]
This was useful. I tried to mv the nvim folder after playing around for sometime, but without removing pack/packer from ~/.local/share/nvim/site, nvim just behaved weird

**Comment by Eezi** [comment]
Nice to hear! :)
